/**
 * VIN WMI (World Manufacturer Identifier) lookup.
 * Maps the first 2–3 characters of a VIN to a brand name.
 * Sources: Wikibooks WMI list + user-provided data.
 *
 * Lookup order: try 3-char prefix first (most specific), then 2-char.
 */

// 3-character WMI → brand
const WMI3: Record<string, string> = {
  // ══════════════════════════════════════
  // === Africa ===
  // ══════════════════════════════════════
  AAA: 'Audi',
  AAK: 'FAW',
  AAM: 'MAN',
  AAP: 'SAPVIN',
  AAV: 'Volkswagen',
  AAW: 'Challenger Trailer',
  ABJ: 'Mitsubishi',
  ABM: 'BMW',
  ACV: 'Isuzu',
  AC5: 'Hyundai',
  ADB: 'Mercedes-Benz',
  ADD: 'UD Trucks',
  ADM: 'General Motors',
  ADN: 'Nissan',
  ADR: 'Renault',
  ADX: 'Tata',
  AFA: 'Ford',
  AFB: 'Mazda',
  AFD: 'BAIC',
  AFZ: 'Fiat',
  AHH: 'Hino',
  AHM: 'Honda',
  AHT: 'Toyota',
  BR1: 'Mercedes-Benz',
  BRY: 'Fiat',
  BUK: 'Kiira Motors',
  CA3: 'MCV',
  DDY: 'Geyushi Motors',

  // ══════════════════════════════════════
  // === Russia ===
  // ══════════════════════════════════════
  EAA: 'Aurus',
  EAN: 'Evolute',
  EAU: 'EVM',
  EBE: 'Sollers',
  EBZ: 'Nizhekotrans',
  ECE: 'XCITE',
  ECW: 'Trans-Alfa',

  // ══════════════════════════════════════
  // === China (H) ===
  // ══════════════════════════════════════
  HA0: 'Sundiro',
  HA6: 'Niu',
  HA7: 'Qingqi',
  HES: 'Smart',
  HGL: 'Farizon',
  HGX: 'Wuling',
  HHZ: 'Huazi',
  HJN: 'Firefly',
  HJR: 'Jetour',
  HJZ: 'Juzhen',
  HJ4: 'BAW',
  HL4: 'Moto Morini',
  HLX: 'Li Auto',
  HRV: 'Henrey',
  HVW: 'Volkswagen',
  HWM: 'Weltmeister',
  HXM: 'Xiaomi',
  HZ2: 'Zhilong',
  H0D: 'Qianxin',
  H0G: 'Wisdom',

  // ══════════════════════════════════════
  // === Japan (J) ===
  // ══════════════════════════════════════
  JAA: 'Isuzu',
  JAB: 'Isuzu',
  JAC: 'Isuzu',
  JAE: 'Acura',
  JAL: 'Isuzu',
  JAM: 'Isuzu',
  JA3: 'Mitsubishi',
  JA4: 'Mitsubishi',
  JA7: 'Mitsubishi',
  JB3: 'Dodge',
  JB4: 'Dodge',
  JB7: 'Dodge',
  JC0: 'Mazda',
  JC1: 'Fiat',
  JC2: 'Mazda',
  JDA: 'Daihatsu',
  JD1: 'Daihatsu',
  JD2: 'Daihatsu',
  JD4: 'Daihatsu',
  JE3: 'Mitsubishi',
  JE4: 'Mitsubishi',
  JF1: 'Subaru',
  JF2: 'Subaru',
  JF3: 'Subaru',
  JF4: 'Subaru',
  JG1: 'Chevrolet',
  JG2: 'Pontiac',
  JG7: 'Pontiac',
  JGC: 'Chevrolet',
  JGT: 'GMC',
  JHA: 'Hino',
  JHB: 'Hino',
  JHD: 'Hino',
  JHF: 'Hino',
  JHH: 'Hino',
  JHL: 'Honda',
  JHM: 'Honda',
  JH1: 'Honda',
  JH2: 'Honda',
  JH3: 'Honda',
  JH4: 'Acura',
  JH6: 'Hino',
  JJ3: 'Chrysler',
  JKA: 'Kawasaki',
  JKB: 'Kawasaki',
  JKM: 'Mitsuoka',
  JKS: 'Suzuki',
  JK8: 'Suzuki',
  JLB: 'Mitsubishi Fuso',
  JLF: 'Mitsubishi Fuso',
  JLS: 'Sterling',
  JL5: 'Mitsubishi Fuso',
  JL6: 'Mitsubishi Fuso',
  JL7: 'Mitsubishi Fuso',
  JMA: 'Mitsubishi',
  JMB: 'Mitsubishi',
  JMF: 'Mitsubishi',
  JMP: 'Mitsubishi',
  JMR: 'Mitsubishi',
  JMY: 'Mitsubishi',
  JMZ: 'Mazda',
  JM0: 'Mazda',
  JM1: 'Mazda',
  JM2: 'Mazda',
  JM3: 'Mazda',
  JM4: 'Mazda',
  JM6: 'Mazda',
  JM7: 'Mazda',
  JNA: 'UD Trucks',
  JNC: 'UD Trucks',
  JNE: 'UD Trucks',
  JNK: 'Infiniti',
  JNR: 'Infiniti',
  JNX: 'Infiniti',
  JN1: 'Nissan',
  JN3: 'Nissan',
  JN6: 'Nissan',
  JN8: 'Nissan',
  JPC: 'UD Trucks',
  JP3: 'Plymouth',
  JP4: 'Plymouth',
  JP7: 'Plymouth',
  JR2: 'Isuzu',
  JSA: 'Suzuki',
  JSK: 'Kawasaki',
  JSL: 'Kawasaki',
  JST: 'Suzuki',
  JS1: 'Suzuki',
  JS2: 'Suzuki',
  JS3: 'Suzuki',
  JS4: 'Suzuki',
  JTB: 'Toyota',
  JTD: 'Toyota',
  JTE: 'Toyota',
  JTF: 'Toyota',
  JTG: 'Toyota',
  JTH: 'Lexus',
  JTJ: 'Lexus',
  JTK: 'Toyota',
  JTL: 'Toyota',
  JTM: 'Toyota',
  JTN: 'Toyota',
  JTP: 'Toyota',
  JT1: 'Toyota',
  JT2: 'Toyota',
  JT3: 'Toyota',
  JT4: 'Toyota',
  JT5: 'Toyota',
  JT6: 'Lexus',
  JT7: 'Toyota',
  JT8: 'Lexus',
  JW6: 'Mitsubishi Fuso',
  JYA: 'Yamaha',
  JYE: 'Yamaha',
  JY3: 'Yamaha',
  JY4: 'Yamaha',
  J81: 'Chevrolet',
  J87: 'Pontiac',
  J8B: 'Chevrolet',
  J8C: 'Chevrolet',
  J8D: 'GMC',
  J8T: 'GMC',
  J8Z: 'Chevrolet',

  // ══════════════════════════════════════
  // === South Korea (K) ===
  // ══════════════════════════════════════
  KF3: 'Merkavim',
  KF6: 'Automotive Industries',
  KLA: 'Daewoo',
  KLP: 'CT&T',
  KLT: 'Tata Daewoo',
  KLU: 'Tata Daewoo',
  KLY: 'Daewoo',
  KL1: 'Chevrolet',
  KL2: 'Pontiac',
  KL3: 'Holden',
  KL4: 'Buick',
  KL5: 'Suzuki',
  KL6: 'GMC',
  KL7: 'Chevrolet',
  KL8: 'Chevrolet',
  KMC: 'Hyundai',
  KME: 'Hyundai',
  KMF: 'Hyundai',
  KMH: 'Hyundai',
  KMJ: 'Hyundai',
  KMT: 'Genesis',
  KMU: 'Genesis',
  KMX: 'Hyundai',
  KMY: 'Daelim',
  KM1: 'Hyosung',
  KM4: 'Hyosung',
  KM8: 'Hyundai',
  KNA: 'Kia',
  KNC: 'Kia',
  KND: 'Kia',
  KNE: 'Kia',
  KNF: 'Kia',
  KNG: 'Kia',
  KNJ: 'Kia',
  KNM: 'Renault',
  KN1: 'Asia Motors',
  KN2: 'Asia Motors',
  KPA: 'SsangYong',
  KPB: 'SsangYong',
  KPD: 'SsangYong',
  KPH: 'Mitsubishi',
  KPT: 'SsangYong',

  // ══════════════════════════════════════
  // === China (L) ===
  // ══════════════════════════════════════
  LAA: 'Jialing',
  LAE: 'Qingqi',
  LAL: 'Sundiro Honda',
  LAN: 'Yamasaki',
  LAP: 'Jianshe',
  LAT: 'Dayang',
  LA6: 'King Long',
  LA7: 'Radar Auto',
  LA8: 'Ankai',
  LBB: 'Qianjiang',
  LBE: 'Hyundai',
  LBM: 'Zongshen Piaggio',
  LBP: 'Yamaha',
  LBV: 'BMW',
  LBX: 'Kinroad',
  LBZ: 'Yeksan',
  LB1: 'Mercedes-Benz',
  LB2: 'Geely',
  LB3: 'Geely',
  LB4: 'Yinxiang',
  LB5: 'Fosti',
  LB7: 'New Summit',
  LCE: 'CFMOTO',
  LCR: 'Gonow',
  LC0: 'BYD',
  LC2: 'Kymco',
  LC6: 'Suzuki',
  LDB: 'Dadi',
  LDC: 'Peugeot',
  LDD: 'Huanghai',
  LDF: 'Fulu',
  LDK: 'FAW Bus',
  LDN: 'Mitsubishi',
  LDP: 'Dongfeng',
  LDY: 'Zhongtong',
  LD3: 'Zontes',
  LD5: 'Benzhou',
  LEC: 'Qingyuan',
  LEF: 'JMC',
  LEH: 'Riya',
  LET: 'Isuzu',
  LEW: 'Dongfeng',
  LE4: 'Mercedes-Benz',
  LE8: 'Hua\'Nan',
  LFB: 'Hongqi',
  LFF: 'Wangye',
  LFG: 'Chuanl',
  LFJ: 'Keyton',
  LFM: 'Toyota',
  LFN: 'FAW Bus',
  LFP: 'Bestune',
  LFT: 'FAW',
  LFU: 'Lifeng',
  LFV: 'Volkswagen',
  LFW: 'FAW',
  LFX: 'Sany',
  LFY: 'Changshu',
  LFZ: 'Leapmotor',
  LF3: 'Lifan',
  LGA: 'Dongfeng',
  LGB: 'Nissan',
  LGC: 'Dongfeng',
  LGF: 'Dongfeng',
  LGG: 'Forthing',
  LGJ: 'Dongfeng',
  LGL: 'Guilin Daewoo',
  LGV: 'Guoji Nanlian',
  LGW: 'Great Wall',
  LGX: 'BYD',
  LGZ: 'Denway',
  LG6: 'Dayun',
  LHA: 'Shuanghuan',
  LHB: 'BAIC',
  LHG: 'Honda',
  LHJ: 'Bashan',
  LHM: 'Dongfeng Renault',
  LHW: 'CRRC',
  LH0: 'Weltmeister',
  LH1: 'FAW-Haima',
  LJC: 'Jincheng',
  LJD: 'Kia',
  LJM: 'Sunlong',
  LJN: 'Zhengzhou Nissan',
  LJR: 'CIMC',
  LJS: 'Yaxing',
  LJU: 'Lotus',
  LJV: 'Sinotruk',
  LJW: 'Landwind',
  LJX: 'JMC Ford',
  LJ1: 'Nio',
  LJ4: 'Jmstar',
  LJ5: 'Jinlun',
  LJ8: 'Zotye',
  LKC: 'BAIC',
  LKG: 'Youngman',
  LKH: 'Hafei',
  LKL: 'Higer Bus',
  LKT: 'Lifan Junma',
  LK2: 'JAC Bus',
  LK6: 'Wuling',
  LK8: 'Yule',
  LLC: 'Loncin',
  LLJ: 'Xinling',
  LLN: 'Qoros',
  LLP: 'Jiajue',
  LLU: 'Dongfeng',
  LLV: 'Lifan',
  LLX: 'Yudo',
  LL0: 'Yongfu',
  LL2: 'Weltmeister',
  LL3: 'Golden Dragon',
  LL6: 'GAC Mitsubishi',
  LL8: 'Yamaha',
  LMC: 'Suzuki',
  LME: 'Skyworth',
  LMF: 'Zhongyu',
  LMG: 'GAC',
  LMH: 'Motoleader',
  LMP: 'Geely',
  LMV: 'Haima',
  LMW: 'GAC',
  LMX: 'Forthing',
  LM0: 'Wangye',
  LM6: 'SWM',
  LM8: 'Seres',
  LNA: 'GAC',
  LNB: 'BAIC',
  LND: 'JMEV',
  LNE: 'CRRC',
  LNN: 'Chery',
  LNP: 'MG',
  LNV: 'Naveco',
  LNX: 'Dongfeng',
  LNY: 'Yuejin',
  LPA: 'DS',
  LPE: 'BYD',
  LPS: 'Polestar',
  LP6: 'Haojian',
  LRB: 'Buick',
  LRD: 'Foton Daimler',
  LRE: 'Cadillac',
  LRP: 'Rato',
  LRR: 'Longjia',
  LRW: 'Tesla',
  LR4: 'Yadi',
  LR6: 'Dayun',
  LSC: 'Changan',
  LSF: 'SAIC',
  LSG: 'Chevrolet',
  LSH: 'SAIC Maxus',
  LSJ: 'MG',
  LSK: 'SAIC Maxus',
  LSV: 'Volkswagen',
  LSY: 'Brilliance',
  LS3: 'Hejia',
  LS4: 'Changan',
  LS5: 'Changan',
  LS6: 'Changan',
  LS7: 'JMC',
  LS8: 'Shaolin',
  LTA: 'ZX Auto',
  LTN: 'Soueast',
  LTP: 'NEVS',
  LTV: 'Toyota',
  LTW: 'Enovate',
  LT1: 'Tonghua',
  LUC: 'Honda',
  LUD: 'Dongfeng Nissan Diesel',
  LUG: 'Qiantu',
  LUJ: 'Shanqi Tianying',
  LUR: 'Chery',
  LUX: 'Dongfeng Yulon',
  LUZ: 'Neta',
  LVA: 'Foton',
  LVB: 'Foton',
  LVC: 'Foton',
  LVF: 'Changhe Suzuki',
  LVG: 'Toyota',
  LVH: 'Honda',
  LVM: 'Chery',
  LVP: 'DFSK',
  LVR: 'Mazda',
  LVS: 'Ford',
  LVT: 'Chery',
  LVU: 'Jetour',
  LVV: 'Chery',
  LVX: 'Aiways',
  LVY: 'Volvo',
  LVZ: 'DFSK',
  LV3: 'Hengchi',
  LV7: 'Qingqi',
  LWB: 'Wuyang Honda',
  LWE: 'Yangtse',
  LWG: 'Huansong',
  LWL: 'Qingling Isuzu',
  LWM: 'Wonjan',
  LWV: 'Jeep',
  LWX: 'Wanxiang',
  LW4: 'Li Auto',
  LXA: 'Qipai',
  LXD: 'Dongfang Lingyun',
  LXG: 'XCMG',
  LXK: 'Meitian',
  LXM: 'SYM',
  LXN: 'Link Tour',
  LXV: 'Borgward',
  LXW: 'JMC Ford',
  LXY: 'Shineray',
  LX6: 'Huari',
  LX8: 'Xgjao',
  LYB: 'Yaxing',
  LYD: 'Kaitong',
  LYJ: 'ZhongdaYanjing',
  LYM: 'Yamaha',
  LYS: 'Vmoto',
  LYU: 'Huansu',
  LYV: 'Volvo',
  LY4: 'Yingang',
  LZE: 'Isuzu',
  LZF: 'SAIC Hongyan',
  LZG: 'Shacman',
  LZK: 'Sinotruk',
  LZL: 'Haili',
  LZM: 'MAN',
  LZP: 'Baotian',
  LZS: 'Zongshen',
  LZU: 'Isuzu',
  LZW: 'Wuling',
  LZY: 'Yutong',
  LZZ: 'Sinotruk',
  LZ0: 'Wuzheng',
  LZ4: 'Linzhi',
  L1K: 'Hengtong',
  L1N: 'XPeng',
  L10: 'Geely Emgrand',
  L2B: 'Baodiao',
  L2C: 'Jaguar',
  L3H: 'Victory',
  L37: 'Zhenhua',
  L4B: 'Xingyue',
  L4F: 'Eagle Electric',
  L4H: 'Longjia',
  L4S: 'Xingyue',
  L4Y: 'Qingqi Rhon',
  L5C: 'Kangdi',
  L5E: 'Zoomlion',
  L5K: 'Yongkang Easy',
  L5N: 'Taotao',
  L5Y: 'Znen',
  L6F: 'Liangzi',
  L6J: 'Kayo',
  L6K: 'Howhit',
  L6T: 'Geely',
  L66: 'Granton',
  L82: 'Baotian',
  L85: 'Huabao',
  L8A: 'Youngman',
  L8X: 'Summit',
  L8Y: 'Jonway',
  L9G: 'Guangtong',
  L9N: 'Taotao',

  // ══════════════════════════════════════
  // === India (M) ===
  // ══════════════════════════════════════
  MAA: 'Kawasaki',
  MAB: 'Mahindra',
  MAC: 'Mahindra',
  MAH: 'Fiat',
  MAJ: 'Ford',
  MAK: 'Honda',
  MAL: 'Hyundai',
  MAN: 'Eicher',
  MAT: 'Tata',
  MA1: 'Mahindra',
  MA3: 'Suzuki',
  MA6: 'General Motors',
  MA7: 'Hindustan Motors',
  MA8: 'Daewoo',
  MBF: 'Royal Enfield',
  MBH: 'Suzuki',
  MBJ: 'Toyota',
  MBK: 'MAN',
  MBL: 'Hero MotoCorp',
  MBR: 'Mercedes-Benz',
  MBU: 'Swaraj',
  MBV: 'Premier',
  MBX: 'Piaggio',
  MBY: 'Asia Motor Works',
  MB1: 'Ashok Leyland',
  MB2: 'Hyundai',
  MB7: 'Mahindra Reva',
  MB8: 'Suzuki',
  MCA: 'Fiat',
  MCB: 'General Motors',
  MCD: 'Mahindra',
  MCG: 'Atul Auto',
  MCL: 'International Cars',
  MC1: 'Force Motors',
  MC2: 'Eicher',
  MC4: 'Dilip Chhabria',
  MDE: 'Kinetic',
  MDH: 'Nissan',
  MDT: 'Kerala Automobiles',
  MD2: 'KTM',
  MD6: 'TVS',
  MD7: 'LML',
  MD9: 'Shuttle Cars',
  MEC: 'BharatBenz',
  MEE: 'Renault',
  MEG: 'Harley-Davidson',
  MER: 'Benelli',
  MES: 'Mahindra Navistar',
  MET: 'Piaggio',
  MEX: 'Škoda',
  ME1: 'Yamaha',
  ME3: 'Royal Enfield',
  ME4: 'Honda',
  MYH: 'Ather Energy',
  MZB: 'Kia',
  MZD: 'Jawa',
  MZZ: 'Citroën',
  MZ7: 'MG',
  M3G: 'Isuzu',
  M6F: 'UM Lohia',

  // ══════════════════════════════════════
  // === Indonesia (MH) ===
  // ══════════════════════════════════════
  MF3: 'Hyundai',
  MHD: 'Suzuki',
  MHF: 'Toyota',
  MHK: 'Daihatsu',
  MHL: 'Mercedes-Benz',
  MHR: 'Honda',
  MHY: 'Suzuki',
  MH1: 'Honda',
  MH3: 'Yamaha',
  MH4: 'Kawasaki',
  MH8: 'Suzuki',
  MJB: 'General Motors',
  MKF: 'DFSK',
  MK2: 'Mitsubishi',
  MK3: 'Wuling',

  // ══════════════════════════════════════
  // === Thailand (ML/MM/MN/MP/MR) ===
  // ══════════════════════════════════════
  MLB: 'Yamaha',
  MLC: 'Suzuki',
  MLE: 'Yamaha',
  MLH: 'Honda',
  MLW: 'Sco Motor',
  MLY: 'Harley-Davidson',
  ML0: 'Ducati',
  ML3: 'Mitsubishi',
  ML5: 'Kawasaki',
  MMA: 'Mitsubishi',
  MMB: 'Mitsubishi',
  MMC: 'Mitsubishi',
  MMD: 'Mitsubishi',
  MME: 'Mitsubishi',
  MMF: 'BMW',
  MML: 'MG',
  MMM: 'Chevrolet',
  MMR: 'Subaru',
  MMS: 'Suzuki',
  MMT: 'Mitsubishi',
  MMU: 'Holden',
  MM0: 'Mazda',
  MM6: 'Mazda',
  MM7: 'Mazda',
  MM8: 'Mazda',
  MNA: 'Ford',
  MNB: 'Ford',
  MNC: 'Ford',
  MNK: 'Hino',
  MNT: 'Nissan',
  MNU: 'Great Wall',
  MN3: 'Mitsubishi',
  MPA: 'Isuzu',
  MPB: 'Ford',
  MP1: 'Isuzu',
  MP2: 'Mazda',
  MP3: 'Plymouth',
  MP5: 'Foton',
  MRH: 'Honda',
  MRT: 'Neta',
  MR0: 'Toyota',
  MR1: 'Toyota',
  MR2: 'Toyota',
  MR3: 'Toyota',
  MS0: 'Super Seven Stars',
  MS1: 'Super Seven Stars',
  MS3: 'Suzuki',
  MXB: 'Saryarka',
  MXL: 'Yutong',
  MXV: 'Ural',
  MX3: 'Hyundai',

  // ══════════════════════════════════════
  // === Iran/Pakistan/Turkey (N) ===
  // ══════════════════════════════════════
  NAA: 'Iran Khodro',
  NAC: 'Mammut',
  NAD: 'Škoda',
  NAL: 'Maral',
  NAP: 'Pars Khodro',
  NAS: 'SAIPA',
  NFB: 'Honda',
  NG3: 'Lucky Motor',
  NLA: 'Honda',
  NLC: 'Askam',
  NLE: 'Mercedes-Benz',
  NLF: 'Koluman',
  NLH: 'Hyundai',
  NLJ: 'Hyundai',
  NLN: 'Karsan',
  NLR: 'Otokar',
  NLT: 'Temsa',
  NLZ: 'Tezeller',
  NL1: 'TOGG',
  NL2: 'HABAS',
  NMA: 'MAN',
  NMB: 'Mercedes-Benz',
  NMC: 'BMC',
  NMH: 'Honda',
  NMS: 'Otoyol',
  NMT: 'Toyota',
  NM0: 'Ford',
  NM1: 'Renault',
  NM4: 'Fiat',
  NNA: 'Isuzu',
  NRE: 'Bozankaya',
  NRX: 'Musoshi',
  NRY: 'Pilotcar',
  NSA: 'SamAvto',
  NS2: 'MAN',
  NVA: 'Khazar',

  // ══════════════════════════════════════
  // === Philippines/Malaysia/Singapore (P) ===
  // ══════════════════════════════════════
  PAB: 'Isuzu',
  PAD: 'Honda',
  PE1: 'Ford',
  PE3: 'Mazda',
  PFD: 'Hyundai',
  PL1: 'Proton',
  PL8: 'Hyundai',
  PLP: 'Subaru',
  PLZ: 'Isuzu',
  PMA: 'MAN',
  PMH: 'Honda',
  PMK: 'Honda',
  PML: 'Hicom',
  PMN: 'Modenas',
  PMS: 'Suzuki',
  PMV: 'Yamaha',
  PMY: 'Yamaha',
  PM1: 'BMW',
  PM2: 'Perodua',
  PNA: 'Peugeot',
  PNS: 'SKSBUS',
  PNV: 'Volvo',
  PN1: 'Toyota',
  PN2: 'Toyota',
  PN8: 'Nissan',
  PPP: 'Suzuki',
  PPV: 'Volkswagen',
  PP1: 'Mazda',
  PP3: 'Hyundai',
  PRA: 'Sinotruk',
  PRH: 'Chery',
  PRN: 'GAC',
  PRX: 'Kia',
  PR8: 'Ford',
  PV3: 'Ford',

  // ══════════════════════════════════════
  // === Taiwan (RF/RK) ===
  // ══════════════════════════════════════
  RFB: 'Kymco',
  RFC: 'Golden Bee',
  RFD: 'Tai Ling',
  RFG: 'SYM',
  RFL: 'Adly',
  RFT: 'CPI',
  RFV: 'PGO',
  RF3: 'Aeon',
  RF5: 'Luxgen',
  RF8: 'EVT',
  RGS: 'Kawasaki',
  RHA: 'Ford',
  RKJ: 'Prince Motors',
  RKL: 'Toyota',
  RKM: 'China Motor',
  RKR: 'Yamaha',
  RKT: 'Access Motor',
  RK3: 'Honda',
  RK7: 'Kawasaki',

  // ══════════════════════════════════════
  // === Vietnam (RL) ===
  // ══════════════════════════════════════
  RLA: 'Mitsubishi',
  RLC: 'Yamaha',
  RLE: 'Isuzu',
  RLH: 'Honda',
  RLL: 'VinFast',
  RLM: 'Mercedes-Benz',
  RLN: 'VinFast',
  RLV: 'Can-Am',
  RL0: 'Ford',
  RL4: 'Toyota',
  RP8: 'Piaggio',
  RUN: 'Sollers',

  // ══════════════════════════════════════
  // === Hong Kong (R1/R2/R3) ===
  // ══════════════════════════════════════
  R1J: 'Jiayuan',
  R1N: 'Niu',
  R10: 'ZAP',
  R2P: 'Evoke',
  R3M: 'Mangosteen',
  R36: 'Shansu',
  R4N: 'Elyx',
  R82: 'Lantu',

  // ══════════════════════════════════════
  // === Europe – UK (S) ===
  // ══════════════════════════════════════
  SAA: 'Austin',
  SAB: 'Switch Mobility',
  SAD: 'Jaguar',
  SAF: 'ERF',
  SAH: 'Honda',
  SAJ: 'Jaguar',
  SAL: 'Land Rover',
  SAM: 'Morris',
  SAR: 'Rover',
  SAT: 'Triumph',
  SAX: 'Austin-Rover',
  SAY: 'Norton',
  SAZ: 'Freight Rover',
  SA3: 'Ginetta',
  SBB: 'Leyland',
  SBC: 'Iveco Ford',
  SBF: 'Nugent',
  SBJ: 'Leyland Bus',
  SBL: 'Leyland',
  SBM: 'McLaren',
  SBS: 'Scammell',
  SBU: 'United Trailers',
  SBV: 'Kenworth',
  SBW: 'Weightlifter',
  SB1: 'Toyota',
  SCA: 'Rolls-Royce',
  SCB: 'Bentley',
  SCC: 'Lotus',
  SCD: 'Reliant',
  SCE: 'DeLorean',
  SCF: 'Aston Martin',
  SCG: 'Triumph',
  SCK: 'Ifor Williams',
  SCM: 'Grove',
  SCR: 'LEVC',
  SCV: 'Volvo',
  SC5: 'Wrightbus',
  SC6: 'INEOS',
  SDB: 'Talbot',
  SDC: 'SDC Trailers',
  SDF: 'Dodge',
  SDG: 'Renault Trucks',
  SDK: 'Caterham',
  SDL: 'TVR',
  SDP: 'MG',
  SDU: 'Utility',
  SD7: 'Aston Martin',
  SD8: 'Moke',
  SED: 'Opel',
  SEG: 'Dennis Eagle',
  SEP: 'Don-Bur',
  SEY: 'LDV',
  SFA: 'Ford',
  SFD: 'Alexander Dennis',
  SFE: 'Alexander Dennis',
  SFR: 'Fruehauf',
  SFN: 'Foden',
  SFZ: 'Tesla',
  SGA: 'Avondale',
  SGB: 'Bailey',
  SGD: 'Swift',
  SGE: 'Elddis',
  SGL: 'Lunar',
  SG4: 'Coachman',
  SHH: 'Honda',
  SHS: 'Honda',
  SH7: 'INEOS',
  SJA: 'Bentley',
  SJB: 'Brian James',
  SJK: 'Infiniti',
  SJN: 'Nissan',
  SJ1: 'Ree Automotive',
  SKA: 'Vauxhall',
  SKB: 'Kel-Berg',
  SKF: 'Bedford',
  SKL: 'Anaig',
  SLA: 'Rolls-Royce',
  SLC: 'Thwaites',
  SLG: 'McMurtry',
  SLN: 'Niftylift',
  SLP: 'JCB',
  SLV: 'Volvo',
  SMR: 'Montracon',
  SMT: 'Triumph',
  SMW: 'Cartwright',
  SMX: 'Gray & Adams',

  // === Europe – East Germany ===
  SNE: 'Wartburg',
  SNT: 'Trabant',
  SNZ: 'MZ',

  // === Europe – Germany misc ===
  SPE: 'B-ON',

  // ══════════════════════════════════════
  // === Europe – Poland (SU/SV/SW/SX/SY/SZ) ===
  // ══════════════════════════════════════
  SUA: 'Autosan',
  SUB: 'Tramp Trail',
  SUC: 'Wiola',
  SUD: 'Wielton',
  SUF: 'Fiat',
  SUG: 'Mega Trailers',
  SUJ: 'Jelcz',
  SUL: 'FSC',
  SUM: 'Novatrail',
  SUP: 'Daewoo',
  SUU: 'Solaris',
  SVH: 'ZASŁAW',
  SVM: 'Inter Cars',
  SVS: 'BODEX',
  SWH: 'Temared',
  SWR: 'Weekend Trailers',
  SWV: 'TA-NO',
  SWZ: 'Zremb',
  SXE: 'Neptun',
  SXK: 'Konar',
  SXM: 'MELEX',
  SXY: 'Wecon',
  SXX: 'Martz',
  SX7: 'Arthur Bus',
  SYB: 'Rydwan',
  SYG: 'Gniotpol',
  SY1: 'Neso Bus',
  SZA: 'Scania',
  SZC: 'Vectrix',
  SZL: 'Boro',
  SZN: 'Głowacz',
  SZR: 'Niewiadów',

  // === Europe – Italy (ST) ===
  ST3: 'Calabrese',

  // ══════════════════════════════════════
  // === Europe – Switzerland/Czech/Hungary (T) ===
  // ══════════════════════════════════════
  TAW: 'NAW',
  TBS: 'Boschung',
  TCC: 'Smart',
  TDM: 'Quantya',
  TEB: 'Bucher',
  TEM: 'Twike',
  TFH: 'FHS Frech-Hoch',
  TJ5: 'Vezeko',
  TKP: 'Panav',
  TKX: 'Agados',
  TKY: 'Metaco',
  TLJ: 'Jawa',
  TMA: 'Hyundai',
  TMB: 'Škoda',
  TMC: 'Hyundai',
  TMK: 'Karosa',
  TMP: 'Škoda',
  TMT: 'Tatra',
  TNA: 'Avia',
  TNE: 'TAZ',
  TNG: 'LIAZ',
  TNT: 'Tatra',
  TNU: 'Tatra',
  TRA: 'Ikarus',
  TRC: 'Csepel',
  TRE: 'Rákos',
  TRK: 'Credo',
  TRR: 'Rába',
  TRU: 'Audi',
  TSB: 'Ikarus',
  TSC: 'Hungary VIN',
  TSE: 'Ikarus',
  TSF: 'Alfabusz',
  TSM: 'Suzuki',
  TSY: 'Keeway',

  // === Europe – Portugal (TW/TX/TY) ===
  TWG: 'CaetanoBus',
  TW0: 'CaetanoBus',
  TW1: 'Toyota',
  TW2: 'Ford',
  TW4: 'UMM',
  TW6: 'Citroën',
  TW7: 'Mini Moke',
  TX5: 'Mini Moke',
  TYA: 'Mitsubishi Fuso',
  TYB: 'Mitsubishi Fuso',

  // === Europe – Serbia ===
  T3C: 'Lohr',

  // === Europe – Netherlands ===
  T7A: 'Ebusco',

  // ══════════════════════════════════════
  // === Europe – Romania/Denmark/Spain (U) ===
  // ══════════════════════════════════════
  UA1: 'AUSA',
  UA2: 'Iveco',
  UA4: 'Irizar',
  UCY: 'Silence',
  UD3: 'Granalu',
  UHE: 'Scanvogn',
  UHL: 'Camp-let',
  UH2: 'Brenderup',
  UJG: 'Garia',
  UKR: 'Hero Camper',
  UMT: 'MTDK',
  UN1: 'Ford',
  UU1: 'Dacia',
  UU2: 'Oltcit',
  UU3: 'ARO',
  UU4: 'Roman',
  UU5: 'Rocar',
  UU6: 'Daewoo',
  UU7: 'Euro Bus Diamond',
  UU9: 'Astra Bus',
  UVW: 'UMM',
  UWR: 'Robus',
  UZT: 'UTB',
  U1A: 'Sanos',
  U1V: 'Van Hool',
  U5Y: 'Kia',
  U6A: 'Granus',
  U6Y: 'Kia',
  U6Z: 'Kia',

  // ══════════════════════════════════════
  // === Europe – Austria/France/Spain (V) ===
  // ══════════════════════════════════════
  VAG: 'Puch',
  VAH: 'Hangler',
  VAK: 'Kässbohrer',
  VAN: 'MAN',
  VAV: 'Schwarzmüller',
  VAX: 'Schwingenschlogel',
  VA0: 'ÖAF',
  VA4: 'KSR',
  VBF: 'Fit-Zel',
  VBK: 'KTM',
  VCF: 'Fisker',
  VFA: 'Alpine',
  VFG: 'Caravelair',
  VFK: 'Fruehauf',
  VFN: 'Trailor',
  VF1: 'Renault',
  VF2: 'Renault Trucks',
  VF3: 'Peugeot',
  VF4: 'Talbot',
  VF5: 'Iveco',
  VF6: 'Renault Trucks',
  VF7: 'Citroën',
  VF8: 'Matra',
  VGA: 'Peugeot',
  VGT: 'ASCA',
  VGU: 'Trouillet',
  VGW: 'BSLT',
  VGX: 'Coder',
  VGY: 'Lohr',
  VG5: 'Yamaha',
  VG6: 'Renault Trucks',
  VG7: 'Renault Trucks',
  VG8: 'Renault Trucks',
  VHR: 'Robuste',
  VHX: 'Potain',
  VH1: 'Benalu',
  VH8: 'Microcar',
  VJR: 'Ligier',
  VJY: 'Gruau',
  VJ1: 'Heuliez Bus',
  VJ2: 'Mia Electric',
  VJ4: 'Gruau',
  VKD: 'Cheval Liberté',
  VK1: 'SEG',
  VK2: 'Grandin',
  VK8: 'Venturi',
  VLG: 'Aixam',
  VLU: 'Scania',
  VL4: 'Bluecar',
  VMK: 'Renault',
  VMS: 'Chatenet',
  VMT: 'SECMA',
  VMW: 'Gépébus',
  VM3: 'Lamberet',
  VN1: 'Renault',
  VN4: 'Voxan',
  VNE: 'Iveco Bus',
  VNK: 'Toyota',
  VNV: 'Nissan',
  VRW: 'Goupil',
  VR1: 'DS',
  VR3: 'Peugeot',
  VR7: 'Citroën',
  VPL: 'Nosmoke',
  VP3: 'Magyar',
  VXE: 'Opel',
  VXF: 'Fiat',
  VXK: 'Opel',
  VYC: 'Lancia',
  VYE: 'Jeep',
  VYF: 'Fiat',
  VYJ: 'Ram',
  VYS: 'Renault',
  VZ2: 'Avtomontaža',

  // === Europe – Spain (VS/VT/VV/VW) ===
  VSA: 'Mercedes-Benz',
  VSC: 'Talbot',
  VSE: 'Suzuki',
  VSF: 'Santana',
  VSK: 'Nissan',
  VSR: 'Leciñena',
  VSS: 'SEAT',
  VSX: 'Opel',
  VSY: 'Renault',
  VS1: 'Pegaso',
  VS5: 'Renault',
  VS6: 'Ford',
  VS7: 'Citroën',
  VS8: 'Peugeot',
  VTD: 'Honda',
  VTH: 'Derbi',
  VTL: 'Yamaha',
  VTM: 'Honda',
  VTP: 'Rieju',
  VTR: 'Gas Gas',
  VTT: 'Suzuki',
  VVC: 'SOR Ibérica',
  VVG: 'Tisvol',
  VV1: 'Lecitrailer',
  VV5: 'Prim-Ball',
  VWA: 'Nissan',
  VWF: 'Guillén',
  VWL: 'Indox',
  VWV: 'Volkswagen',

  // === Europe – Serbia/Croatia (VX/V1-V6) ===
  VXY: 'Neobus',
  VX1: 'Zastava',
  V1Y: 'Sanos',
  V2X: 'Ikarbus',
  V31: 'TAZ',
  V34: 'Crobus',
  V6A: 'Tiki',
  V6B: 'Brentex',
  V6T: 'Verge',
  V61: 'Respo',

  // ══════════════════════════════════════
  // === Europe – Germany (W) ===
  // ══════════════════════════════════════
  WAC: 'Audi',
  WAF: 'Ackermann',
  WAG: 'Neoplan',
  WAP: 'Alpina',
  WAU: 'Audi',
  WA1: 'Audi',
  WBA: 'BMW',
  WBC: 'Boom Trikes',
  WBJ: 'Bitter',
  WBK: 'Böcker',
  WBL: 'Blumhardt',
  WBS: 'BMW',
  WBU: 'Bürstner',
  WBX: 'BMW',
  WBY: 'BMW',
  WB0: 'Böckmann',
  WB1: 'BMW',
  WB2: 'Blyss',
  WB3: 'BMW',
  WB4: 'BMW',
  WB5: 'BMW',
  WCD: 'Freightliner',
  WCM: 'Wilcox',
  WDA: 'Mercedes-Benz',
  WDB: 'Mercedes-Benz',
  WDC: 'Mercedes-Benz',
  WDD: 'Mercedes-Benz',
  WDF: 'Mercedes-Benz',
  WDP: 'Freightliner',
  WDR: 'Freightliner',
  WDT: 'Dethleffs',
  WDW: 'Dodge',
  WDX: 'Dodge',
  WDY: 'Freightliner',
  WDZ: 'Mercedes-Benz',
  WD0: 'Dodge',
  WD1: 'Freightliner',
  WD2: 'Freightliner',
  WD3: 'Mercedes-Benz',
  WD4: 'Mercedes-Benz',
  WD5: 'Freightliner',
  WD6: 'Freightliner',
  WD7: 'Freightliner',
  WD8: 'Dodge',
  WEB: 'EvoBus',
  WEG: 'Ablinger',
  WEL: 'e.GO',
  WFB: 'Feldbinder',
  WFC: 'Fendt',
  WFD: 'Fliegl',
  WFN: 'Tadano Faun',
  WF0: 'Ford',
  WFO: 'Ford',
  WF1: 'Merkur',
  WGB: 'Göppel Bus',
  WG0: 'Goldhofer',
  WHB: 'Hobby',
  WHD: 'Humbaur',
  WHL: 'Hulco',
  WHW: 'Hako',
  WHY: 'Hymer',
  WH7: 'Hüfferman',
  WJM: 'Iveco',
  WJR: 'Irmscher',
  WKE: 'Krone',
  WKK: 'Setra',
  WKN: 'Knaus',
  WKV: 'Kässbohrer',
  WK0: 'Kögel',
  WLA: 'Langendorf',
  WLF: 'Liebherr',
  WMA: 'MAN',
  WME: 'Smart',
  WMW: 'MINI',
  WMX: 'Mercedes-AMG',
  WMZ: 'MINI',
  WNA: 'e.GO',
  WP0: 'Porsche',
  WP1: 'Porsche',
  WPO: 'Porsche',
  WSM: 'Schmitz Cargobull',
  WTA: 'Tabbert',
  WUA: 'Audi',
  WU1: 'Audi',
  WVG: 'Volkswagen',
  WVM: 'Volkswagen',
  WVW: 'Volkswagen',
  WV1: 'Volkswagen',
  WV2: 'Volkswagen',
  WV3: 'Volkswagen',
  WV4: 'Volkswagen',
  WV5: 'Volkswagen',
  WZ1: 'Toyota',
  W04: 'Buick',
  W0L: 'Opel',
  W0V: 'Opel',
  W0S: 'Opel',
  W1A: 'Smart',
  W1K: 'Mercedes-Benz',
  W1N: 'Mercedes-Benz',
  W1T: 'Mercedes-Benz',
  W1V: 'Mercedes-Benz',

  // ══════════════════════════════════════
  // === Europe – Scandinavia/Belgium (Y) ===
  // ══════════════════════════════════════
  YAR: 'Toyota',
  YBC: 'Toyota',
  YBW: 'Volkswagen',
  YK1: 'Saab',
  YSC: 'Cadillac',
  YSM: 'Polestar',
  YSR: 'Polestar',
  YS2: 'Scania',
  YS3: 'Saab',
  YV1: 'Volvo',
  YV2: 'Volvo',
  YV3: 'Volvo',
  YV4: 'Volvo',

  // ══════════════════════════════════════
  // === Europe – Italy (Z) ===
  // ══════════════════════════════════════
  ZAA: 'Alfa Romeo',
  ZAC: 'Jeep',
  ZAM: 'Maserati',
  ZAP: 'Piaggio',
  ZAR: 'Alfa Romeo',
  ZAS: 'Alfa Romeo',
  ZBN: 'Benelli',
  ZCF: 'Iveco',
  ZCG: 'MV Agusta',
  ZD4: 'Aprilia',
  ZDC: 'Honda',
  ZDF: 'Ferrari',
  ZDM: 'Ducati',
  ZDT: 'De Tomaso',
  ZFA: 'Fiat',
  ZFB: 'Fiat',
  ZFC: 'Fiat',
  ZFF: 'Ferrari',
  ZGU: 'Moto Guzzi',
  ZHW: 'Lamborghini',
  ZLA: 'Lancia',
  ZMA: 'Maserati',
  ZN6: 'Maserati',
  ZNN: 'Energica',
  ZPB: 'Lamborghini',
  ZR1: 'Microlino',
  ZSG: 'Ferrari',

  // ══════════════════════════════════════
  // === Russia/Netherlands/Tesla (X) ===
  // ══════════════════════════════════════
  XLB: 'Volvo',
  XLR: 'DAF',
  XMC: 'Mitsubishi',
  XP7: 'Tesla',
  XTA: 'Lada',
  XW7: 'Toyota',
  XW8: 'Volkswagen',

  // ══════════════════════════════════════
  // === North America – US (1) ===
  // ══════════════════════════════════════
  '1AM': 'AMC',
  '1B3': 'Dodge',
  '1B4': 'Dodge',
  '1C3': 'Chrysler',
  '1C4': 'Chrysler',
  '1C6': 'Ram',
  '1FA': 'Ford',
  '1FB': 'Ford',
  '1FD': 'Ford',
  '1FM': 'Ford',
  '1FT': 'Ford',
  '1FU': 'Freightliner',
  '1G1': 'Chevrolet',
  '1G2': 'Pontiac',
  '1G3': 'Oldsmobile',
  '1G4': 'Buick',
  '1G6': 'Cadillac',
  '1G8': 'Saturn',
  '1GC': 'Chevrolet',
  '1GK': 'GMC',
  '1GN': 'Chevrolet',
  '1GT': 'GMC',
  '1GY': 'Cadillac',
  '1HD': 'Harley-Davidson',
  '1HF': 'Honda',
  '1HG': 'Honda',
  '1HS': 'International',
  '1J4': 'Jeep',
  '1VW': 'Volkswagen',
  '1YV': 'Mazda',

  // === North America – Canada (2) ===
  '2FM': 'Ford',
  '2HM': 'Hyundai',

  // === North America – Mexico (3) ===
  '3FA': 'Ford',
  '3FM': 'Ford',
  '3VW': 'Volkswagen',

  // === US (4/5) ===
  '4US': 'BMW',
  '4T1': 'Toyota',
  '4T3': 'Toyota',
  '4T4': 'Toyota',
  '5FN': 'Honda',
  '5J6': 'Honda',
  '5NM': 'Hyundai',
  '5NP': 'Hyundai',
  '5TD': 'Hyundai',
  '5XY': 'Kia',
  '5YJ': 'Tesla',

  // === Oceania (6) ===
  '6F4': 'Nissan',
  '6FP': 'Ford',
  '6MM': 'Mitsubishi',
  '6T1': 'Toyota',

  // === South America (8/9) ===
  '8AP': 'Fiat',
  '8AW': 'Volkswagen',
  '93H': 'Honda',
  '93Y': 'Renault',
  '936': 'Peugeot',
  '9BG': 'Chevrolet',
  '9BW': 'Volkswagen',
  '9BF': 'Ford',

  // === Other notable ===
  B7J: 'Chrysler',
  CL9: 'Wallyscar',
  RA1: 'Steyr',
  S2D: 'Chrysler',
};

// 2-character WMI prefix → brand (less specific, fallback)
const WMI2: Record<string, string> = {
  JA: 'Isuzu',
  JF: 'Subaru',
  JH: 'Honda',
  JM: 'Mazda',
  JN: 'Nissan',
  JS: 'Suzuki',
  JT: 'Toyota',
  KL: 'Daewoo',
  KM: 'Hyundai',
  KN: 'Kia',
  UU: 'Dacia',
  '1C': 'Chrysler',
  '1D': 'Dodge',
  '1F': 'Ford',
  '1G': 'General Motors',
  '1H': 'Honda',
  '1J': 'Jeep',
  '1L': 'Lincoln',
  '1N': 'Nissan',
  '2F': 'Ford',
  '2G': 'General Motors',
  '2H': 'Hyundai',
  '2M': 'Mercury',
  '2T': 'Toyota',
  '3F': 'Ford',
  '3G': 'General Motors',
  '3H': 'Honda',
  '3N': 'Nissan',
  '3V': 'Volkswagen',
  '4F': 'Mazda',
  '4M': 'Mercury',
  '4S': 'Subaru',
  '4T': 'Toyota',
  '4U': 'BMW',
  '5F': 'Honda',
  '5J': 'Honda',
  '5L': 'Lincoln',
  '5N': 'Hyundai',
  '5T': 'Hyundai',
  '5X': 'Kia',
  '5Y': 'Tesla',
  '6F': 'Ford',
  '6H': 'Holden',
  '6T': 'Toyota',
};

/**
 * Look up a brand from a VIN string using the WMI prefix.
 * Returns the brand name or null if not found.
 */
export function lookupBrandFromVin(vin: string): string | null {
  if (!vin || vin.length < 3) return null;
  const upper = vin.toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (upper.length < 3) return null;

  // Try 3-char first
  const wmi3 = upper.substring(0, 3);
  if (WMI3[wmi3]) return WMI3[wmi3];

  // Try 2-char fallback
  const wmi2 = upper.substring(0, 2);
  if (WMI2[wmi2]) return WMI2[wmi2];

  return null;
}

/** Expose maps for admin display */
export const WMI3_MAP = WMI3;
export const WMI2_MAP = WMI2;
