/**
 * VIN WMI (World Manufacturer Identifier) lookup.
 * Maps the first 2–3 characters of a VIN to a brand name.
 * Sources: Wikibooks WMI list + user-provided data.
 *
 * Lookup order: try 3-char prefix first (most specific), then 2-char.
 */

// 3-character WMI → brand
const WMI3: Record<string, string> = {
  // === Africa ===
  AAA: 'Audi',
  AAV: 'Volkswagen',
  ABJ: 'Mitsubishi',
  ABM: 'BMW',
  ACV: 'Isuzu',
  AC5: 'Hyundai',
  ADB: 'Mercedes-Benz',
  ADM: 'General Motors',
  ADN: 'Nissan',
  ADR: 'Renault',
  ADX: 'Tata',
  AFA: 'Ford',
  AFB: 'Mazda',
  AFD: 'BAIC',
  AFZ: 'Fiat',
  AHH: 'Hino',
  AHM: 'Honda',
  AHT: 'Toyota',

  // === China (H) ===
  HES: 'Smart',
  HLX: 'Li Auto',
  HVW: 'Volkswagen',
  HXM: 'Xiaomi',

  // === Japan (J) ===
  JAA: 'Isuzu',
  JAB: 'Isuzu',
  JAC: 'Isuzu',
  JAE: 'Acura',
  JA3: 'Mitsubishi',
  JA4: 'Mitsubishi',
  JA7: 'Mitsubishi',
  JDA: 'Daihatsu',
  JD1: 'Daihatsu',
  JD2: 'Daihatsu',
  JF1: 'Subaru',
  JF2: 'Subaru',
  JF3: 'Subaru',
  JHA: 'Hino',
  JHL: 'Honda',
  JHM: 'Honda',
  JH1: 'Honda',
  JH2: 'Honda',
  JH3: 'Honda',
  JH4: 'Acura',
  JKA: 'Kawasaki',
  JKB: 'Kawasaki',
  JMA: 'Mitsubishi',
  JMB: 'Mitsubishi',
  JMF: 'Mitsubishi',
  JMP: 'Mitsubishi',
  JMR: 'Mitsubishi',
  JMY: 'Mitsubishi',
  JMZ: 'Mazda',
  JM0: 'Mazda',
  JM1: 'Mazda',
  JM2: 'Mazda',
  JM3: 'Mazda',
  JM6: 'Mazda',
  JNK: 'Infiniti',
  JNR: 'Infiniti',
  JN1: 'Nissan',
  JN3: 'Nissan',
  JN6: 'Nissan',
  JN8: 'Nissan',
  JSA: 'Suzuki',
  JS1: 'Suzuki',
  JS2: 'Suzuki',
  JS3: 'Suzuki',
  JTB: 'Toyota',
  JTD: 'Toyota',
  JTE: 'Toyota',
  JTF: 'Toyota',
  JTG: 'Toyota',
  JTH: 'Lexus',
  JTJ: 'Lexus',
  JTK: 'Toyota',
  JTL: 'Toyota',
  JTM: 'Toyota',
  JTN: 'Toyota',
  JTP: 'Toyota',
  JT1: 'Toyota',
  JT2: 'Toyota',
  JT3: 'Toyota',
  JT4: 'Toyota',
  JT6: 'Lexus',
  JT8: 'Lexus',
  JYA: 'Yamaha',

  // === South Korea (K) ===
  KLA: 'Daewoo',
  KLY: 'Daewoo',
  KL1: 'Chevrolet',
  KMC: 'Hyundai',
  KMH: 'Hyundai',
  KMT: 'Genesis',
  KMU: 'Genesis',
  KM8: 'Hyundai',
  KNA: 'Kia',
  KNC: 'Kia',
  KND: 'Kia',
  KNE: 'Kia',
  KNM: 'Renault',
  KPA: 'SsangYong',
  KPB: 'SsangYong',
  KPT: 'SsangYong',

  // === China (L) ===
  LBE: 'Hyundai',
  LBV: 'BMW',
  LB3: 'Geely',
  LCE: 'CFMOTO',
  LC0: 'BYD',
  LDC: 'Peugeot',
  LDN: 'Mitsubishi',
  LDP: 'Dongfeng',
  LFB: 'Hongqi',
  LFM: 'Toyota',
  LFP: 'Bestune',
  LFV: 'Volkswagen',
  LFZ: 'Leapmotor',
  LGB: 'Nissan',
  LGW: 'Great Wall',
  LGX: 'BYD',
  LHG: 'Honda',
  LJD: 'Kia',
  LJU: 'Lotus',
  LJ1: 'Nio',
  LK6: 'Wuling',
  LME: 'Skyworth',
  LMG: 'GAC',
  LM8: 'Seres',
  LNA: 'GAC',
  LNB: 'BAIC',
  LNN: 'Chery',
  LPA: 'DS',
  LPE: 'BYD',
  LPS: 'Polestar',
  LRW: 'Tesla',
  LSF: 'SAIC',
  LSG: 'Chevrolet',
  LSJ: 'MG',
  LSV: 'Volkswagen',
  LS5: 'Changan',
  LS6: 'Changan',
  LTV: 'Toyota',
  LUC: 'Honda',
  LUR: 'Chery',
  LUZ: 'Neta',
  LVG: 'Toyota',
  LVH: 'Honda',
  LVR: 'Mazda',
  LVS: 'Ford',
  LVT: 'Chery',
  LVV: 'Chery',
  LVX: 'Aiways',
  LVY: 'Volvo',
  LW4: 'Li Auto',
  L1N: 'XPeng',
  L2C: 'Jaguar',
  L6T: 'Geely',

  // === India (M) ===
  MAB: 'Mahindra',
  MAH: 'Fiat',
  MAJ: 'Ford',
  MAK: 'Honda',
  MAL: 'Hyundai',
  MAT: 'Tata',
  MA3: 'Suzuki',
  MBJ: 'Toyota',
  MBR: 'Mercedes-Benz',
  MB2: 'Hyundai',
  MCA: 'Fiat',
  MDH: 'Nissan',
  MD2: 'KTM',
  MEE: 'Renault',
  MEX: 'Škoda',
  ME4: 'Honda',
  MF3: 'Hyundai',
  MHD: 'Suzuki',
  MHF: 'Toyota',
  MHK: 'Daihatsu',
  MHL: 'Mercedes-Benz',
  MHR: 'Honda',
  MHY: 'Suzuki',
  MK2: 'Mitsubishi',
  MMB: 'Mitsubishi',
  MZB: 'Kia',
  MZZ: 'Citroën',
  MZ7: 'MG',

  // === Europe – UK (S) ===
  SAJ: 'Jaguar',
  SAL: 'Land Rover',
  SB1: 'Toyota',
  SBM: 'McLaren',
  SCA: 'Rolls-Royce',
  SCB: 'Bentley',
  SCC: 'Lotus',
  SCE: 'DeLorean',
  SCF: 'Aston Martin',
  SC6: 'INEOS',
  SDK: 'Caterham',
  SDL: 'TVR',
  SDP: 'MG',
  SFA: 'Ford',
  SHH: 'Honda',
  SHS: 'Honda',
  SJA: 'Bentley',
  SJK: 'Infiniti',
  SJN: 'Nissan',
  SKA: 'Vauxhall',
  SLA: 'Rolls-Royce',
  SMT: 'Triumph',

  // === Europe – Germany (SN/W) ===
  SUF: 'Fiat',
  SUP: 'Daewoo',
  SUU: 'Solaris',

  // === Europe – Switzerland/Czech/Hungary (T) ===
  TCC: 'Smart',
  TMA: 'Hyundai',
  TMB: 'Škoda',
  TMC: 'Hyundai',
  TMT: 'Tatra',
  TNT: 'Tatra',
  TRU: 'Audi',
  TSM: 'Suzuki',

  // === Europe – Romania/Denmark (U) ===
  UU1: 'Dacia',
  U5Y: 'Kia',
  U6Y: 'Kia',
  U6Z: 'Kia',

  // === Europe – Austria/France/Spain (V) ===
  VBK: 'KTM',
  VFA: 'Alpine',
  VF1: 'Renault',
  VF3: 'Peugeot',
  VF6: 'Renault',
  VF7: 'Citroën',
  VNK: 'Toyota',
  VNV: 'Nissan',
  VR1: 'DS',
  VR3: 'Peugeot',
  VR7: 'Citroën',
  VXK: 'Opel',
  VYS: 'Renault',
  VSA: 'Mercedes-Benz',
  VSE: 'Suzuki',
  VSK: 'Nissan',
  VSS: 'SEAT',
  VSX: 'Opel',
  VS5: 'Renault',
  VS6: 'Ford',
  VS7: 'Citroën',
  VS8: 'Peugeot',
  VWV: 'Volkswagen',

  // === Europe – Germany (W) ===
  WAC: 'Audi',
  WAG: 'Neoplan',
  WAP: 'Alpina',
  WAU: 'Audi',
  WA1: 'Audi',
  WBA: 'BMW',
  WBS: 'BMW',
  WBX: 'BMW',
  WBY: 'BMW',
  WB1: 'BMW',
  WB5: 'BMW',
  WDA: 'Mercedes-Benz',
  WDB: 'Mercedes-Benz',
  WDC: 'Mercedes-Benz',
  WDD: 'Mercedes-Benz',
  WDF: 'Mercedes-Benz',
  WEB: 'EvoBus',
  WEL: 'e.GO',
  WF0: 'Ford',
  WFO: 'Ford',
  WHB: 'Hobby',
  WJM: 'Iveco',
  WKK: 'Setra',
  WMA: 'MAN',
  WME: 'Smart',
  WMW: 'MINI',
  WMX: 'Mercedes-AMG',
  WMZ: 'MINI',
  WNA: 'e.GO',
  WP0: 'Porsche',
  WP1: 'Porsche',
  WPO: 'Porsche',
  WSM: 'Schmitz Cargobull',
  WTA: 'Tabbert',
  WUA: 'Audi',
  WU1: 'Audi',
  WVG: 'Volkswagen',
  WVM: 'Volkswagen',
  WVW: 'Volkswagen',
  WV1: 'Volkswagen',
  WV2: 'Volkswagen',
  WV3: 'Volkswagen',
  WV4: 'Volkswagen',
  WV5: 'Volkswagen',
  WZ1: 'Toyota',
  W04: 'Buick',
  W0L: 'Opel',
  W0V: 'Opel',
  W0S: 'Opel',
  W1A: 'Smart',
  W1K: 'Mercedes-Benz',
  W1N: 'Mercedes-Benz',
  W1T: 'Mercedes-Benz',
  W1V: 'Mercedes-Benz',

  // === Europe – Scandinavia/Belgium (Y) ===
  YAR: 'Toyota',
  YBC: 'Toyota',
  YBW: 'Volkswagen',
  YK1: 'Saab',
  YSC: 'Cadillac',
  YSM: 'Polestar',
  YSR: 'Polestar',
  YS2: 'Scania',
  YS3: 'Saab',
  YV1: 'Volvo',
  YV2: 'Volvo',
  YV3: 'Volvo',
  YV4: 'Volvo',

  // === Europe – Italy (Z) ===
  ZAA: 'Alfa Romeo',
  ZAC: 'Jeep',
  ZAM: 'Maserati',
  ZAP: 'Piaggio',
  ZAR: 'Alfa Romeo',
  ZAS: 'Alfa Romeo',
  ZBN: 'Benelli',
  ZCF: 'Iveco',
  ZCG: 'MV Agusta',
  ZD4: 'Aprilia',
  ZDC: 'Honda',
  ZDF: 'Ferrari',
  ZDM: 'Ducati',
  ZDT: 'De Tomaso',
  ZFA: 'Fiat',
  ZFB: 'Fiat',
  ZFC: 'Fiat',
  ZFF: 'Ferrari',
  ZGU: 'Moto Guzzi',
  ZHW: 'Lamborghini',
  ZLA: 'Lancia',
  ZMA: 'Maserati',
  ZN6: 'Maserati',
  ZNN: 'Energica',
  ZPB: 'Lamborghini',
  ZR1: 'Microlino',
  ZSG: 'Ferrari',

  // === Russia/Netherlands/Tesla ===
  XLB: 'Volvo',
  XLR: 'DAF',
  XMC: 'Mitsubishi',
  XP7: 'Tesla',
  XTA: 'Lada',
  XW7: 'Toyota',
  XW8: 'Volkswagen',

  // === North America – US (1) ===
  '1AM': 'AMC',
  '1B3': 'Dodge',
  '1B4': 'Dodge',
  '1C3': 'Chrysler',
  '1C4': 'Chrysler',
  '1C6': 'Ram',
  '1FA': 'Ford',
  '1FB': 'Ford',
  '1FD': 'Ford',
  '1FM': 'Ford',
  '1FT': 'Ford',
  '1FU': 'Freightliner',
  '1G1': 'Chevrolet',
  '1G2': 'Pontiac',
  '1G3': 'Oldsmobile',
  '1G4': 'Buick',
  '1G6': 'Cadillac',
  '1G8': 'Saturn',
  '1GC': 'Chevrolet',
  '1GK': 'GMC',
  '1GN': 'Chevrolet',
  '1GT': 'GMC',
  '1GY': 'Cadillac',
  '1HD': 'Harley-Davidson',
  '1HF': 'Honda',
  '1HG': 'Honda',
  '1HS': 'International',
  '1J4': 'Jeep',
  '1VW': 'Volkswagen',
  '1YV': 'Mazda',

  // === North America – Canada (2) ===
  '2FM': 'Ford',
  '2HM': 'Hyundai',

  // === North America – Mexico (3) ===
  '3FA': 'Ford',
  '3VW': 'Volkswagen',

  // === US (4/5) ===
  '4US': 'BMW',
  '4T1': 'Toyota',
  '4T3': 'Toyota',
  '4T4': 'Toyota',
  '5FN': 'Honda',
  '5J6': 'Honda',
  '5NM': 'Hyundai',
  '5NP': 'Hyundai',
  '5TD': 'Hyundai',
  '5XY': 'Kia',
  '5YJ': 'Tesla',

  // === Oceania (6) ===
  '6F4': 'Nissan',
  '6FP': 'Ford',
  '6MM': 'Mitsubishi',
  '6T1': 'Toyota',

  // === South America (8/9) ===
  '8AP': 'Fiat',
  '8AW': 'Volkswagen',
  '93H': 'Honda',
  '93Y': 'Renault',
  '936': 'Peugeot',
  '9BG': 'Chevrolet',
  '9BW': 'Volkswagen',
  '9BF': 'Ford',

  // === Other notable ===
  B7J: 'Chrysler',
  CL9: 'Wallyscar',
  EAA: 'Aurus',
  LRW: 'Tesla',
  PL1: 'Proton',
  S2D: 'Chrysler',
};

// 2-character WMI prefix → brand (less specific, fallback)
const WMI2: Record<string, string> = {
  JA: 'Isuzu',
  JF: 'Subaru',
  JH: 'Honda',
  JM: 'Mazda',
  JN: 'Nissan',
  JS: 'Suzuki',
  JT: 'Toyota',
  KL: 'Daewoo',
  KM: 'Hyundai',
  KN: 'Kia',
  UU: 'Dacia',
  '1C': 'Chrysler',
  '1D': 'Dodge',
  '1F': 'Ford',
  '1G': 'General Motors',
  '1H': 'Honda',
  '1J': 'Jeep',
  '1L': 'Lincoln',
  '1N': 'Nissan',
  '2F': 'Ford',
  '2G': 'General Motors',
  '2H': 'Hyundai',
  '2M': 'Mercury',
  '2T': 'Toyota',
  '3F': 'Ford',
  '3G': 'General Motors',
  '3H': 'Honda',
  '3N': 'Nissan',
  '3V': 'Volkswagen',
  '4F': 'Mazda',
  '4M': 'Mercury',
  '4S': 'Subaru',
  '4T': 'Toyota',
  '4U': 'BMW',
  '5F': 'Honda',
  '5J': 'Honda',
  '5L': 'Lincoln',
  '5N': 'Hyundai',
  '5T': 'Hyundai',
  '5X': 'Kia',
  '5Y': 'Tesla',
  '6F': 'Ford',
  '6H': 'Holden',
  '6T': 'Toyota',
};

/**
 * Look up a brand from a VIN string using the WMI prefix.
 * Returns the brand name or null if not found.
 */
export function lookupBrandFromVin(vin: string): string | null {
  if (!vin || vin.length < 3) return null;
  const upper = vin.toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (upper.length < 3) return null;

  // Try 3-char first
  const wmi3 = upper.substring(0, 3);
  if (WMI3[wmi3]) return WMI3[wmi3];

  // Try 2-char fallback
  const wmi2 = upper.substring(0, 2);
  if (WMI2[wmi2]) return WMI2[wmi2];

  return null;
}

/** Expose maps for admin display */
export const WMI3_MAP = WMI3;
export const WMI2_MAP = WMI2;
