import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, ChevronRight, CarFront, FileText, Image as ImageIcon, BadgeEuro, MapPin, MessageCircle, CalendarDays, Search, ShieldCheck, Globe2, Megaphone, Smartphone, ClipboardList, CircleHelp, Sparkle, Clock3 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import FunnelLayout from '@/components/funnel/FunnelLayout';
import { usePageMeta } from '@/hooks/usePageMeta';
import { captureAttribution, captureLastTouch } from '@/lib/funnel-attribution';
import { trackFunnelEvent } from '@/lib/funnel-tracking';
import carImage from '@/assets/funnel/standtage-showroom-local.webp';

const TEST_URL = '/fahrzeug-testen?source=landingpages';
const problems = [
  { icon: Search, title: 'Google Ads', text: 'Eine konkrete Kampagne bewirbt ein Fahrzeug oder Angebot, der Klick landet aber auf einer allgemeinen Fahrzeugliste.' },
  { icon: Smartphone, title: 'Social Ads', text: 'Das beworbene Fahrzeug ist attraktiv, aber der Besucher muss sich danach selbst durch die Website suchen.' },
  { icon: Globe2, title: 'SEO', text: 'Modelle, Motorisierungen und Angebote könnten eigene relevante Einstiegsseiten sein, werden aber nicht gezielt genutzt.' },
  { icon: ClipboardList, title: 'Standard-Fahrzeugdetailseite', text: 'Viele Daten, aber keine klare Verkaufsführung und kein aktiver nächster Schritt.' },
];
const classic = ['Fahrzeug auswählen', 'Daten zusammensuchen', 'Texte schreiben', 'Bilder aufbereiten', 'Finanzierung berechnen', 'Leasing einbauen', 'Pflichtangaben prüfen', 'Seite bauen', 'Formulare einrichten', 'Tracking', 'Veröffentlichen'];
const steps = [
  { title: 'Fahrzeug auswählen', text: 'VIN, Fahrzeugdaten, Bilder und Angebot übernehmen.', icon: CarFront },
  { title: 'autohaus.ai baut die Seite', text: 'Highlights, Bilder, Preise, Finanzierung, Leasing, Verbrauchswerte, Kontaktmöglichkeiten und suchrelevante Inhalte werden strukturiert zusammengeführt.', icon: FileText },
  { title: 'Interessenten werden weitergeführt', text: 'Fragen beantworten, Bedarf erkennen, Lead qualifizieren, Probefahrt oder Termin anstoßen.', icon: MessageCircle },
];
const campaigns = [
  { icon: Search, channel: 'Google Ads', query: '„Golf GTI finanzieren“', text: 'Eine Seite für genau dieses Fahrzeug und sein Finanzierungsangebot.' },
  { icon: Megaphone, channel: 'Social Ads', query: '„Unser Angebot der Woche“', text: 'Eine Aktionsseite mit Fahrzeug, Rate und direkter Anfrage.' },
  { icon: Globe2, channel: 'SEO', query: '„BMW X3 Leasing Hanau“', text: 'Eine indexierbare Modell- oder Angebotsseite mit passendem Inhalt.' },
];
const sources = [
  ['VIN / Fahrzeugbestand', 'Modell, Motorisierung, Ausstattung'], ['Fahrzeugbilder', 'Galerie und Motive'], ['Preisdaten', 'Verkaufspreis und Aktionen'],
  ['Finanzierung', 'Laufzeit, Anzahlung, Rate'], ['Leasing', 'Laufzeit, Kilometer, Rate'], ['WLTP', 'Verbrauch, CO₂, Pflichtangaben'], ['Autohausdaten', 'Standort, Zeiten, Ansprechpartner'],
];
const chat = [
  ['Kunde', 'Hat der Wagen eine Anhängerkupplung?'], ['Assistent', 'Ja, dieses Fahrzeug ist mit einer schwenkbaren Anhängerkupplung ausgestattet.'],
  ['Kunde', 'Was kostet der mit 5.000 € Anzahlung?'], ['Assistent', 'Ich kann Ihnen dafür eine passende Finanzierungsvariante zeigen.'],
  ['Kunde', 'Kann ich ihn Samstag fahren?'], ['Assistent', 'Gerne. Soll ich Ihnen einen Probefahrttermin anfragen?'],
];
const faq: [string, string][] = [
  ['Kann ich die Landingpage für Google Ads nutzen?', 'Ja. Sie können Kampagnen auf eine passende Fahrzeug- oder Angebotsseite führen. Anzeigeninhalt und Zielseite sollten zueinander passen.'],
  ['Kann ich für verschiedene Fahrzeuge eigene Seiten erstellen?', 'Ja. Jedes Fahrzeug kann eine eigene Seite mit seinen Daten, Bildern und Angeboten erhalten.'],
  ['Können Finanzierung und Leasing eingebunden werden?', 'Ja, sofern die jeweiligen Angebotsdaten vorliegen. Konditionen und erforderliche Angaben sollten vor Veröffentlichung geprüft werden.'],
  ['Wie werden WLTP- und Verbrauchsdaten dargestellt?', 'Vorhandene Verbrauchs- und CO₂-Daten werden in den vorgesehenen Pflichtangaben dargestellt. Fehlende oder unklare Angaben müssen vor Veröffentlichung ergänzt und geprüft werden.'],
  ['Kann der Verkaufsassistent Fragen zu meinem Autohaus beantworten?', 'Er kann die für ihn freigegebenen Informationen zu Fahrzeugen, Angeboten, Standorten und Abläufen nutzen. Antworten hängen von den hinterlegten Daten ab.'],
  ['Kann der Assistent Probefahrten anfragen?', 'Er kann den Wunsch aufnehmen und eine Anfrage anstoßen. Eine bestätigte Buchung entsteht erst nach Rückmeldung Ihres Autohauses.'],
  ['Hilft die Landingpage auch bei SEO?', 'Eine sauber aufgebaute, indexierbare Seite kann zusätzliche relevante Einstiegspunkte schaffen. Eine bestimmte Platzierung in Suchmaschinen lässt sich nicht garantieren.'],
];

function DemoChat({ compact = false }: { compact?: boolean }) {
  return <div className="min-w-0 overflow-hidden rounded-lg border border-border bg-card shadow-card">
    <div className="flex items-center gap-2 border-b border-border bg-secondary/60 px-4 py-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-accent/10"><MessageCircle className="h-4 w-4 text-accent" /></span><div><p className="text-xs font-bold">Ihr Verkaufsassistent</p><p className="text-[11px] text-muted-foreground">Beispielgespräch</p></div></div>
    <div className={`space-y-3 p-4 ${compact ? 'text-[11px]' : 'text-sm'}`}>
      {(compact ? chat.slice(0, 4) : chat).map(([who, text], i) => <div key={i} className={`flex ${who === 'Kunde' ? 'justify-end' : 'justify-start'}`}><p className={`max-w-[90%] rounded-lg px-3 py-2 leading-relaxed ${who === 'Kunde' ? 'bg-primary text-primary-foreground' : 'bg-secondary text-foreground'}`}>{text}</p></div>)}
      {!compact && <div className="rounded-md border border-accent/30 bg-accent/5 px-3 py-2 text-center text-xs font-bold text-accent">Probefahrt anfragen <ArrowRight className="inline h-3 w-3" /></div>}
    </div>
  </div>;
}

function DealerPage({ hero = false }: { hero?: boolean }) {
  return <div className="min-w-0 overflow-hidden rounded-lg border border-border bg-card shadow-elevated">
    <div className="flex items-center justify-between border-b border-border px-4 py-2.5"><span className="font-display text-sm font-bold">AUTOHAUS MUSTER</span><span className="text-[10px] text-muted-foreground">Fahrzeuge · Angebote · Kontakt</span></div>
    <div className="relative"><img src={carImage} alt="Beispielhaftes Fahrzeug im Showroom" className={`w-full object-cover ${hero ? 'aspect-[16/9]' : 'aspect-[2.4/1]'}`} /> <span className="absolute bottom-3 left-3 rounded bg-card/95 px-2 py-1 text-[10px] font-semibold shadow-card">Beispiel einer Fahrzeugseite</span></div>
    <div className="p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-accent">Im Bestand · Beispiel</p><h3 className="font-display text-lg font-bold sm:text-2xl">BMW X3 · Ihr nächstes Fahrzeug</h3><p className="text-xs text-muted-foreground">Komfort · Ausstattung · Fahrfreude</p></div><div className="text-left sm:text-right"><p className="text-lg font-bold">Preis auf Anfrage</p><p className="text-xs text-muted-foreground">Finanzierung & Leasing auf Anfrage</p></div></div>
    <div className="mt-4 flex flex-wrap gap-2">{['Ausstattung', 'Galerie', 'Finanzierung', 'Leasing', 'Verbrauch & CO₂'].map(t => <span key={t} className="rounded border border-border bg-secondary/50 px-2 py-1 text-[10px] font-medium">{t}</span>)}</div>
    <div className="mt-5 grid gap-3 border-t border-border pt-4 sm:grid-cols-2"><div className="space-y-3"><p className="text-xs font-bold">Fahrzeug-Highlights & Galerie</p><div className="grid grid-cols-3 gap-1.5">{[0,1,2].map(i => <img key={i} src={carImage} alt="" className="aspect-[4/3] w-full rounded object-cover" />)}</div><p className="text-[11px] text-muted-foreground">Ausstattung · Standort · Ansprechpartner</p></div><div className="rounded-md bg-secondary/60 p-3"><p className="text-xs font-bold">Ihr Angebot auf einen Blick</p><p className="mt-1 text-[11px] text-muted-foreground">Finanzierungsrechner · Leasingoptionen · Konditionen</p><p className="mt-2 text-[11px] text-muted-foreground">WLTP-Verbrauch und CO₂-Werte entsprechend den Fahrzeugdaten; Pflichtangaben vor Veröffentlichung prüfen.</p><span className="mt-3 block rounded bg-accent px-3 py-2 text-center text-xs font-bold text-accent-foreground">Probefahrt anfragen</span></div></div>
    </div>
  </div>;
}

export default function AutohausLandingpages() {
  usePageMeta({ title: 'Fahrzeug-Landingpages & digitaler Verkaufsassistent | autohaus.ai', description: 'Vom Fahrzeug bis zum Kunden: fahrzeugbezogene Verkaufsseiten mit Bildern, Angebot und digitalem Verkaufsassistenten für Autohäuser.', canonicalPath: '/autohaus-landingpages' });
  useEffect(() => { captureAttribution('lp_landingpages'); captureLastTouch(); }, []);
  useEffect(() => {
    const sent = new Set<number>();
    const onScroll = () => { const max = document.documentElement.scrollHeight - window.innerHeight; if (max <= 0) return; const pct = window.scrollY / max * 100; for (const t of [50, 90]) if (pct >= t && !sent.has(t)) { sent.add(t); trackFunnelEvent('scroll_depth', { step: `scroll_${t}`, percent: t }); } };
    window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll);
  }, []);
  return <FunnelLayout ctaHref={TEST_URL} ctaLabel="Landingpage testen" anchors={[{href:'#ablauf',label:"So funktioniert's"},{href:'#landingpage',label:'Landingpage'},{href:'#assistent',label:'Assistent'},{href:'#fragen',label:'Fragen'}]}>
    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[.92fr_1.08fr] lg:py-16"><div className="min-w-0"><p className="text-xs font-bold uppercase text-accent">Für Autohäuser &amp; Fahrzeughändler</p><h1 className="mt-4 font-display text-4xl font-bold leading-[1.06] sm:text-5xl">Gute Werbung braucht eine Seite, die verkauft.</h1><p className="mt-4 font-display text-xl font-bold text-accent">Aus Fahrzeugdaten wird automatisch Ihre Verkaufs-Landingpage.</p><p className="mt-5 text-sm leading-7 text-muted-foreground sm:text-base">VIN, Ausstattung, Bilder, Finanzierung, Leasing und gesetzlich erforderliche Verbrauchsangaben: autohaus.ai baut daraus eine vollständige Fahrzeug-Landingpage. Ein integrierter Verkaufsassistent beantwortet Fragen, qualifiziert Interessenten und führt sie bis zur Probefahrt.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="w-full shadow-glow sm:w-auto"><Link to={TEST_URL} data-cta="landingpages_test">Landingpage für ein Fahrzeug testen <ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline" size="lg" className="w-full sm:w-auto"><a href="#ablauf">So funktioniert es <ChevronRight className="h-4 w-4" /></a></Button></div><p className="mt-5 text-xs text-muted-foreground">Fahrzeugdaten · Finanzierung · WLTP · Lead-Assistent</p></div>
    <div className="min-w-0"><div className="grid grid-cols-2 gap-2 sm:gap-3"><div className="rounded-lg border border-border bg-secondary/60 p-3 sm:p-4"><p className="text-[10px] font-bold uppercase text-accent">01 · Daten</p><p className="mt-2 text-xs font-bold">Ihr Fahrzeugbestand</p><p className="mt-1 break-all text-[10px] text-muted-foreground">VIN · Bilder · Ausstattung · Angebot</p><img src={carImage} alt="Fahrzeug aus dem Bestand" className="mt-3 aspect-[16/9] w-full rounded object-cover" /></div><div className="row-span-2 min-w-0"><p className="mb-2 text-[10px] font-bold uppercase text-accent">02 · Landingpage</p><DealerPage hero /></div><div className="min-w-0"><p className="mb-2 text-[10px] font-bold uppercase text-accent">03 · Gespräch</p><DemoChat compact /></div></div><div className="mt-3 flex items-center gap-2 rounded-lg border border-accent/25 bg-accent/5 p-3 text-xs font-bold text-accent"><CalendarDays className="h-4 w-4 shrink-0" />04 · Qualifizierte Anfrage → Probefahrt angefragt</div><p className="mt-2 text-[11px] text-muted-foreground">Daten → Landingpage → Gespräch → Termin · beispielhafte Darstellung</p></div></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="max-w-3xl font-display text-3xl font-bold leading-tight">Die Anzeige bringt den Klick. Aber die Seite muss den Verkauf übernehmen.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{problems.map(({icon:Icon,title,text}) => <div key={title} className="rounded-lg border border-border bg-card p-5 shadow-card"><Icon className="h-6 w-6 text-accent" /><h3 className="mt-4 font-display font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div><p className="mt-8 max-w-3xl font-display text-xl font-bold">Der teuerste Klick ist der, der auf einer Seite endet, die den Interessenten allein lässt.</p></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="max-w-3xl font-display text-3xl font-bold">Eine gute Landingpage kostet heute Zeit. Und genau deshalb wird sie oft nicht gebaut.</h2><ol className="mt-7 flex gap-2 overflow-x-auto pb-3 [scrollbar-width:thin]">{classic.map((s,i)=><li key={s} className="flex shrink-0 items-center gap-2"><span className="rounded-md border border-border bg-secondary/60 px-3 py-2 text-xs font-semibold"><span className="mr-2 text-accent">{String(i+1).padStart(2,'0')}</span>{s}</span>{i<classic.length-1&&<ChevronRight className="h-4 w-4 text-muted-foreground" />}</li>)}</ol><p className="mt-4 text-sm font-semibold text-muted-foreground">Und beim nächsten Fahrzeug beginnt der Prozess von vorn.</p></div></section>
    <section id="ablauf" className="scroll-mt-20 border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="text-xs font-bold uppercase text-accent">Aufnehmen → vermarkten → verkaufen</p><h2 className="mt-2 font-display text-3xl font-bold">Vom Fahrzeugdatensatz zur fertigen Verkaufsseite.</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{steps.map(({title,text,icon:Icon},i)=><div key={title} className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-accent"/><span className="font-display text-2xl font-bold text-accent/40">0{i+1}</span></div><h3 className="mt-5 font-display text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div><p className="mt-7 font-display text-2xl font-bold text-accent">Nicht nur eine Landingpage. Eine digitale Verkaufsstrecke.</p></div></section>
    <section id="landingpage" className="scroll-mt-20 border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Alles, was ein Interessent für seine Entscheidung braucht.</h2><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Eine passende Fahrzeugseite statt einer allgemeinen Liste. Beispielhaft dargestellt, mit Ihren Daten und Ihrem Angebot.</p><div className="mt-8 grid items-start gap-5 lg:grid-cols-[1.55fr_.65fr]"><DealerPage /><div className="min-w-0"><DemoChat /><div className="mt-4 grid grid-cols-2 gap-2">{['Galerie & Highlights','Ausstattung','Finanzierung & Leasing','Verbrauch & WLTP','Standort & Kontakt','Probefahrt-Anfrage'].map(t=><p key={t} className="flex gap-1.5 rounded border border-border bg-secondary/50 p-2 text-[11px] font-medium"><Check className="h-3.5 w-3.5 shrink-0 text-accent" />{t}</p>)}</div></div></div></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Eine Kampagne. Eine Botschaft. Eine passende Landingpage.</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{campaigns.map(({icon:Icon,channel,query,text})=><div key={channel} className="rounded-lg border border-border bg-card p-5 shadow-card"><Icon className="h-6 w-6 text-accent"/><p className="mt-4 text-xs font-bold uppercase text-accent">{channel}</p><h3 className="mt-1 font-display text-lg font-bold">{query}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">→ {text}</p></div>)}</div><p className="mt-6 font-display text-xl font-bold">Nicht jeder Besucher braucht dieselbe Seite.</p></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Die Seite kennt das Fahrzeug.</h2><div className="mt-7 grid items-center gap-5 lg:grid-cols-[1fr_auto_.7fr_auto_.8fr]"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{sources.map(([a,b])=><p key={a} className="rounded-md border border-border bg-secondary/40 px-3 py-2 text-xs"><strong className="block">{a}</strong><span className="text-muted-foreground">{b}</span></p>)}</div><ArrowRight className="mx-auto h-5 w-5 rotate-90 text-accent lg:rotate-0"/><div className="rounded-lg border border-accent/30 bg-accent/10 px-5 py-8 text-center font-display text-xl font-bold text-accent">autohaus.ai</div><ArrowRight className="mx-auto h-5 w-5 rotate-90 text-accent lg:rotate-0"/><div className="rounded-lg border border-border bg-secondary/40 p-3"><img src={carImage} alt="Fahrzeugseite als Ergebnis" className="aspect-video w-full rounded object-cover" loading="lazy"/><p className="mt-3 text-center text-sm font-bold">Fertige Fahrzeug-Landingpage</p></div></div></div></section>
    <section id="assistent" className="scroll-mt-20 border-b border-border bg-secondary/45 py-14"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 sm:px-6 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase text-accent">Digitale Beratung</p><h2 className="mt-2 font-display text-3xl font-bold">Ihre Landingpage schläft nicht. Ihr digitaler Verkäufer auch nicht.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Der Verkaufsassistent kennt Ihre Fahrzeuge, Ihre Angebote und Ihren Betrieb. Er beantwortet Interessenten in Ihrem Namen und führt das Gespräch weiter.</p><p className="mt-4 text-xs text-muted-foreground">Das Beispielgespräch setzt hinterlegte Fahrzeugdaten voraus; Probefahrttermine werden angefragt, nicht automatisch bestätigt.</p></div><DemoChat /></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 md:grid-cols-2"><div><h2 className="font-display text-3xl font-bold">Er kennt Ihren Betrieb. Nicht nur das Internet.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Der Assistent greift auf die für ihn freigegebenen Informationen Ihres Autohauses zurück: Fahrzeuge, Angebote, Prozesse, Standorte, Ansprechpartner und häufige Kundenfragen.</p><p className="mt-3 text-xs text-accent">Auf Basis Ihrer eigenen Wissensbasis.</p></div><div className="grid grid-cols-2 gap-2 self-center">{['Fahrzeuge','Angebote','Abläufe','Standorte','Ansprechpartner','Häufige Fragen'].map(t=><div key={t} className="flex items-center gap-2 rounded-md border border-border bg-secondary/50 p-3 text-xs font-semibold"><Check className="h-4 w-4 shrink-0 text-accent"/>{t}</div>)}</div></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Mehr Zeit für die Gespräche, bei denen Sie wirklich gebraucht werden.</h2><div className="mt-7 grid items-center gap-5 md:grid-cols-[1fr_auto_1fr]"><div className="space-y-2">{['Ist das Fahrzeug noch verfügbar?','Welche Ausstattung hat es?','Wie hoch wäre die Rate?','Wann haben Sie geöffnet?','Kann ich eine Probefahrt machen?'].map(t=><p key={t} className="rounded-md border border-border bg-card px-4 py-3 text-sm">{t}</p>)}</div><ArrowRight className="mx-auto h-6 w-6 rotate-90 text-accent md:rotate-0"/><div className="rounded-lg border border-accent/30 bg-card p-6 shadow-card"><p className="text-xs font-bold uppercase text-accent">Qualifizierter Interessent · Beispiel</p><h3 className="mt-3 font-display text-xl font-bold">Anfrage zum BMW X3</h3><dl className="mt-4 space-y-2 text-sm">{[['Interesse','Finanzierung'],['Wunschrate','ca. 550 €'],['Probefahrt','Samstag angefragt'],['Kontakt','Kontaktdaten hinterlegt']].map(([k,v])=><div key={k} className="flex justify-between gap-3 border-b border-border pb-2"><dt className="text-muted-foreground">{k}</dt><dd className="text-right font-semibold">{v}</dd></div>)}</dl><p className="mt-3 text-[11px] text-muted-foreground">Fiktives Beispiel, keine echten Kundendaten oder Konditionen.</p></div></div></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 md:grid-cols-2"><div><h2 className="font-display text-3xl font-bold">Jedes Fahrzeug kann ein eigener Einstiegspunkt werden.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Technisch und inhaltlich sauber aufgebaute Landingpages schaffen zusätzliche relevante Einstiegsseiten für Suchmaschinen. Eine Platzierung wird nicht garantiert.</p></div><div className="space-y-2">{['VW Tiguan Leasing Hanau','BMW X3 finanzieren Frankfurt','Audi A3 Gebrauchtwagen Aschaffenburg'].map(t=><div key={t} className="flex items-center gap-3 rounded-md border border-border bg-secondary/50 p-3 text-sm"><Search className="h-4 w-4 shrink-0 text-accent"/>{t}</div>)}</div></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-7 w-7 shrink-0 text-accent"/><div><h2 className="font-display text-3xl font-bold">Verkaufsstark. Ohne Pflichtangaben zu vergessen.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Die vorgesehenen Felder helfen dabei, wichtige Angaben auf der Seite zu zeigen. Ihre konkreten Angebots- und Fahrzeugdaten müssen vor Veröffentlichung geprüft und gegebenenfalls ergänzt werden.</p></div></div><div className="mt-6 flex flex-wrap gap-2">{['WLTP-Verbrauch','CO₂-Werte','Relevante Pflichtinformationen','Finanzierungsangaben','Leasingangaben','Preisangaben','KI-Kennzeichnung, wo erforderlich'].map(t=><span key={t} className="flex items-center gap-1.5 rounded-md border border-border bg-card px-3 py-2 text-xs font-medium"><Check className="h-3.5 w-3.5 text-accent"/>{t}</span>)}</div></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">So testen Sie autohaus.ai</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[['Fahrzeug / Daten bereitstellen','Laden Sie ein Bild hoch und nennen Sie uns Ihr Autohaus.'],['Beispiel-Landingpage erzeugen','Wir prüfen, wie Ihre Fahrzeugdaten und Ihr Angebot auf einer Seite wirken können.'],['Ergebnis und Verkaufsstrecke prüfen','Sie erhalten eine Rückmeldung im bestehenden schriftlichen Prozess.']].map(([t,d],i)=><div key={t} className="rounded-lg border border-border bg-secondary/50 p-5"><span className="font-display text-2xl font-bold text-accent">0{i+1}</span><h3 className="mt-3 font-display font-bold">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground">{['Nur für Unternehmer','Testdaten werden nicht veröffentlicht','Datenschutz im bestehenden Testprozess','Schriftliche Rückmeldung'].map(t=><p key={t} className="flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-accent"/>{t}</p>)}</div></div></section>
    <section id="fragen" className="scroll-mt-20 border-b border-border bg-secondary/45 py-14"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase text-accent">Häufige Fragen</p><h2 className="mt-2 font-display text-3xl font-bold">Noch Fragen?</h2><p className="mt-3 text-sm text-muted-foreground">Alles Wichtige zur Fahrzeugseite und digitalen Beratung.</p></div><Accordion type="single" collapsible className="space-y-3">{faq.map(([q,a],i)=><AccordionItem key={q} value={`faq-${i}`} className="rounded-lg border border-border bg-card px-5 shadow-card last:border-b"><AccordionTrigger className="text-left text-sm font-semibold hover:no-underline">{q}</AccordionTrigger><AccordionContent className="text-sm leading-6 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="px-4 py-14 sm:px-6"><div className="gradient-hero mx-auto max-w-6xl rounded-lg px-6 py-10 text-primary-foreground sm:px-10 sm:py-14"><h2 className="font-display text-3xl font-bold sm:text-4xl">Schalten Sie nicht nur Werbung.</h2><p className="mt-2 font-display text-xl font-bold">Bauen Sie den Weg bis zur Probefahrt gleich mit.</p><p className="mt-4 max-w-2xl text-sm leading-6 text-primary-foreground/85">Ein Fahrzeug, seine Daten und Ihr Angebot reichen als Ausgangspunkt. autohaus.ai macht daraus die passende Landingpage und begleitet den Interessenten weiter.</p><Button asChild size="lg" variant="secondary" className="mt-6 w-full sm:w-auto"><Link to={TEST_URL} data-cta="landingpages_test">Landingpage für ein Fahrzeug testen <ArrowRight className="h-4 w-4"/></Link></Button><p className="mt-3 text-xs text-primary-foreground/80">Fahrzeugdaten · Finanzierung · WLTP · Lead-Assistent</p></div></section>
  </FunnelLayout>;
}
