import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Camera, Car, Check, FileText, Images, Megaphone, Network, Plug, RotateCcw, Video } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import FunnelLayout from '@/components/funnel/FunnelLayout';
import BeforeAfterShowcase from '@/components/funnel/BeforeAfterShowcase';
import ProcessCheckForm from '@/components/funnel/ProcessCheckForm';
import { usePageMeta } from '@/hooks/usePageMeta';
import { captureAttribution } from '@/lib/funnel-attribution';

const TEST_URL='/fahrzeug-testen?source=marketing';
const FLOW=[[Car,'Fahrzeug kommt an','Der Prozess startet direkt bei der Fahrzeugannahme.'],[Camera,'Foto & Daten','Aufnahmen und Fahrzeugdaten werden einmalig erfasst.'],[Images,'Professionelle Bilder','Einheitliche Fahrzeugbilder für alle Ausspielwege.'],[Megaphone,'Kanäle bespielen','Banner, Social, Video, Verkaufsseiten und 360°.']] as const;
const MODULES=[[Images,'Fahrzeugbilder','Einheitliche Außen- und Innenaufnahmen aus vorhandenen Fotos.'],[RotateCcw,'360°-Ansicht','Interaktive Rundumansichten auf Basis derselben Aufnahmen.'],[Megaphone,'Banner & Social','Werbemittel in den passenden Formaten für Ihre Kanäle.'],[Video,'Video','Kurze Fahrzeugvideos für Reels, Stories und Portale.'],[FileText,'Verkaufsseiten','Fahrzeugseiten inklusive Pflichtangaben und Kontaktstrecke.'],[Plug,'Integrationen & API','Übergabe an bestehende Systeme und digitale Ausspielwege.']] as const;
const FAQ=[['Lässt sich der Prozess über mehrere Betriebe ausrollen?','Ja. Der Ablauf ist für jeden Standort identisch und schafft eine vergleichbare Bild- und Contentqualität.'],['Können bestehende Systeme angebunden werden?','Je nach Setup stehen API, WordPress, FTP/SFTP und Einbettungsmöglichkeiten zur Verfügung.'],['Wer erstellt die Inhalte im Betrieb?','Die Aufnahmen entstehen im Betrieb, die Verarbeitung übernimmt autohaus.ai. Zusätzliche Bildbearbeitungskenntnisse sind nicht erforderlich.'],['Wie starten wir am besten?','Mit einem echten Fahrzeug aus Ihrem Bestand oder einem kurzen Prozesscheck für Ihre Händlergruppe.']];

export default function AutohausMarketing(){
 usePageMeta({title:'Fahrzeugmarketing für Autohäuser | autohaus.ai',description:'Ein Prozess von der Fahrzeugankunft bis zum fertigen Online-Auftritt: Bilder, 360°, Banner, Video und Verkaufsseiten.',canonicalPath:'/autohaus-marketing'});
 useEffect(()=>{captureAttribution('lp_marketing');},[]);
 return <FunnelLayout ctaHref={TEST_URL} ctaLabel="Mit Fahrzeug testen" anchors={[{href:'#workflow',label:'Workflow'},{href:'#module',label:'Funktionen'},{href:'#prozess-check',label:'Prozesscheck'},{href:'#faq',label:'FAQ'}]}>
  <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:py-16"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-accent">Fahrzeugmarketing für Autohäuser</p><h1 className="mt-4 font-display text-4xl font-bold leading-[1.04] sm:text-5xl">Ein Fahrzeug. Ein Prozess. Alle Marketingkanäle.</h1><p className="mt-5 text-base leading-7 text-muted-foreground">autohaus.ai verbindet Fahrzeugbilder, Inhalte und digitale Vermarktung – vom eintreffenden Fahrzeug bis zum vollständigen Online-Auftritt.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link to={TEST_URL}>Mit einem Fahrzeug testen <ArrowRight className="h-4 w-4" /></Link></Button><Button asChild size="lg" variant="outline"><a href="#prozess-check">Prozesscheck für Gruppen</a></Button></div><div className="mt-5 flex flex-wrap gap-4 text-xs text-muted-foreground">{['Einmal erfassen','Mehrfach ausspielen','Standortübergreifend'].map(x=><span key={x} className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-accent"/>{x}</span>)}</div></div><BeforeAfterShowcase /></div></section>
  <section id="workflow" className="mx-auto max-w-6xl scroll-mt-20 px-4 py-14 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-accent">Vom Point of Arrival zum Verkauf</p><h2 className="mt-2 font-display text-3xl font-bold">Der vollständige Workflow im Überblick</h2><div className="mt-7 grid gap-4 md:grid-cols-4">{FLOW.map(([Icon,title,text],i)=><article key={title} className="rounded-lg border border-border bg-card p-5 shadow-card"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-accent/10 text-accent"><Icon className="h-5 w-5"/></span><p className="mt-5 text-xs font-bold text-accent">0{i+1}</p><h3 className="mt-1 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></section>
  <section className="funnel-section-tint border-y border-border py-14"><div className="mx-auto grid max-w-6xl gap-5 px-4 sm:px-6 lg:grid-cols-2"><div className="rounded-lg border border-destructive/20 bg-destructive/5 p-6"><h2 className="font-display text-xl font-bold">Wo Händlergruppen Zeit verlieren</h2><ul className="mt-5 space-y-3 text-sm text-muted-foreground">{['Medienbrüche zwischen Einkauf, Aufbereitung und Marketing','Unterschiedliche Qualität je Standort','Hoher Agentur- und Personalaufwand','Fahrzeuge ohne vollständigen Online-Auftritt'].map(x=><li key={x} className="flex gap-3"><span className="font-bold text-destructive">×</span>{x}</li>)}</ul></div><div className="rounded-lg border border-accent/20 bg-accent/5 p-6"><h2 className="font-display text-xl font-bold">Ein Prozess statt Insellösungen</h2><ul className="mt-5 space-y-3 text-sm text-muted-foreground">{['Einheitliche Standards über alle Betriebe','Wiederverwendbare Assets für jeden Kanal','Nachvollziehbarer Ablauf vom Foto bis zur Ausgabe','Zentral steuerbar und standortübergreifend einsetzbar'].map(x=><li key={x} className="flex gap-3"><Check className="h-4 w-4 shrink-0 text-accent"/>{x}</li>)}</ul></div></div></section>
  <section id="module" className="mx-auto max-w-6xl scroll-mt-20 px-4 py-14 sm:px-6"><h2 className="font-display text-3xl font-bold">Alle Bausteine für Ihre Fahrzeugvermarktung</h2><p className="mt-2 text-sm text-muted-foreground">Eine Plattform, modular passend zu Ihrem Betrieb und Ihren Kanälen.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{MODULES.map(([Icon,title,text])=><article key={title} className="rounded-lg border border-border bg-card p-5 shadow-card"><Icon className="h-5 w-5 text-accent"/><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></section>
  <section className="border-y border-border bg-secondary/45 py-14"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-2"><div><Network className="h-7 w-7 text-accent"/><h2 className="mt-4 font-display text-2xl font-bold">Für einen Standort oder eine ganze Gruppe</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Der Ablauf bleibt identisch und schafft einen verlässlichen Standard, unabhängig von Betrieb, Mitarbeiter oder Fahrzeugmenge.</p></div><div className="grid gap-3 sm:grid-cols-3">{[['API','Programmatischer Zugriff'],['WordPress','Einbindung in Websites'],['FTP / SFTP','Automatisierte Übergabe']].map(([a,b])=><div key={a} className="rounded-lg border border-border bg-card p-4"><p className="font-bold">{a}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{b}</p></div>)}</div></div></section>
  <section id="prozess-check" className="mx-auto grid max-w-6xl scroll-mt-20 gap-8 px-4 py-14 sm:px-6 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-accent">Für Händlergruppen</p><h2 className="mt-2 font-display text-3xl font-bold">Passt der Ablauf zu Ihrer Organisation?</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Mit vier Angaben prüfen wir Volumen und Standortstruktur. Ein Bild-Upload ist dafür nicht nötig.</p></div><ProcessCheckForm/></section>
  <section id="faq" className="border-t border-border bg-card py-14"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-accent">Häufige Fragen</p><h2 className="mt-2 font-display text-3xl font-bold">Fragen zum Einsatz</h2></div><Accordion type="single" collapsible>{FAQ.map(([q,a],i)=><AccordionItem key={q} value={`f${i}`}><AccordionTrigger className="text-left text-sm font-semibold">{q}</AccordionTrigger><AccordionContent className="text-sm leading-6 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
  <section className="px-4 py-12 sm:px-6"><div className="gradient-hero mx-auto flex max-w-6xl flex-col justify-between gap-6 rounded-lg px-6 py-8 text-primary-foreground lg:flex-row lg:items-center"><div><h2 className="font-display text-2xl font-bold">Starten Sie mit einem echten Fahrzeug aus Ihrem Bestand.</h2><p className="mt-2 text-sm text-primary-foreground/80">So sehen Sie direkt, wie der Ablauf zu Ihrem Betrieb passt.</p></div><Button asChild size="lg" variant="secondary"><Link to={TEST_URL}>Fahrzeug testen <ArrowRight className="h-4 w-4"/></Link></Button></div></section>
 </FunnelLayout>;
}
