import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, ChevronRight, Play, Film, Camera, Scissors, Smartphone, MonitorPlay, Megaphone, Clapperboard, Palette, RefreshCw, ShieldCheck, X, Sparkles, Clock3, Layers3 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import FunnelLayout from '@/components/funnel/FunnelLayout';
import { usePageMeta } from '@/hooks/usePageMeta';
import { captureAttribution, captureLastTouch } from '@/lib/funnel-attribution';
import { trackFunnelEvent } from '@/lib/funnel-tracking';
import carImage from '@/assets/funnel/standtage-showroom-local.webp';

const TEST_URL = '/fahrzeug-testen?source=videos';
const classicLine = ['Idee', 'Termin', 'Fahrzeug vorbereiten', 'Kamera', 'Dreh', 'mehrere Takes', 'Schnitt', 'Musik', 'Text', 'Untertitel', 'Export', 'Formate anpassen', 'Veröffentlichen'];
const problems = [
  { icon: Camera, title: 'Jeder Dreh wird zum Projekt.', text: 'Videograf, Termin und Fahrzeug müssen zusammenpassen.' },
  { icon: Scissors, title: 'Der eigentliche Aufwand beginnt nach dem Dreh.', text: 'Material sichten, schneiden, vertonen, texten und freigeben.' },
  { icon: MonitorPlay, title: 'Jeder Kanal braucht ein eigenes Format.', text: 'Reel, Story, TikTok, YouTube und Ads brauchen unterschiedliche Varianten.' },
  { icon: Clock3, title: 'Deshalb bleibt Video oft liegen.', text: 'Das Fahrzeug ist da, aber der Content fehlt.' },
];
const classic = ['Videograf buchen', 'Termin abstimmen', 'Fahrzeug vorbereiten', 'Dreh durchführen', 'Material sichten', 'Schneiden', 'Vertonen', 'Animieren', 'Formate exportieren', 'Veröffentlichen'];
const short = [['Fahrzeug auswählen', 'Mit vorhandenen Fahrzeugbildern und Daten starten.'], ['Video-Stil wählen', 'Wirkung und Format für den gewünschten Kanal bestimmen.'], ['Video erzeugen', 'Ergebnis prüfen und für den Kanal verwenden.']];
const videoKinds = [
  { name: 'Produktvideo', desc: 'Elegante Kamerafahrten, Details und Innenraum.', ratio: 'aspect-video', tag: 'Fahrzeug im Fokus', position: 'object-center', icon: Film },
  { name: 'Social Reel', desc: 'Dynamisch, hochkant und aufmerksamkeitsstark.', ratio: 'aspect-[4/5]', tag: 'Im Blick bleiben', position: 'object-left', icon: Smartphone },
  { name: 'Angebotsvideo', desc: 'Fahrzeug, Angebot und klare Handlungsaufforderung.', ratio: 'aspect-video', tag: 'Angebot entdecken', position: 'object-right', icon: Megaphone },
  { name: 'YouTube Short', desc: 'Fahrzeug-Highlights kompakt erzählt.', ratio: 'aspect-[4/5]', tag: 'Das Wichtigste zuerst', position: 'object-center', icon: Play },
  { name: 'Imagefilm-Style', desc: 'Hochwertig und emotional inszeniert.', ratio: 'aspect-video', tag: 'Ein starker Auftritt', position: 'object-left', icon: Sparkles },
  { name: 'Video Ad', desc: 'Einstieg, Fahrzeug, Angebot und nächster Schritt.', ratio: 'aspect-video', tag: 'Jetzt Fahrzeug ansehen', position: 'object-right', icon: Clapperboard },
];
const channels = [
  { name: 'Instagram', text: 'Reels, Stories und Videos für den Feed.', format: '9:16 · 4:5' },
  { name: 'TikTok', text: 'Kurze Fahrzeugclips mit einem starken Einstieg.', format: '9:16' },
  { name: 'YouTube', text: 'Shorts und klassische Fahrzeugvideos.', format: '9:16 · 16:9' },
  { name: 'Ads', text: 'Videoanzeigen für fahrzeugbezogene Kampagnen.', format: 'Hochkant · Quer' },
];
const styles = ['Showroom', 'Urban', 'Premium', 'Sport', 'Launch', 'Futuristisch', 'Angebotsvideo', 'Modell-Highlight'];
const benefits = [
  { icon: Camera, title: 'Keine Videoproduktion koordinieren', text: 'Kein Termin, kein Team, kein Drehplan für wiederkehrenden Fahrzeug-Content.' },
  { icon: MonitorPlay, title: 'Für jeden Kanal passend', text: 'Hochformat, Querformat, Social, Ads und YouTube.' },
  { icon: Palette, title: 'Immer im eigenen Look', text: 'Logo, Farben, CI und Kampagnenstil können einheitlich bleiben.' },
  { icon: Layers3, title: 'Mehr Fahrzeuge sichtbar machen', text: 'Nicht nur einzelne Topmodelle bekommen Video-Content.' },
];
const faq: [string, string][] = [
  ['Welche Videoformate können erstellt werden?', 'Je nach gewähltem Stil und Ausgangsmaterial sind Hoch- und Querformate für Social Media, YouTube und Werbeanzeigen vorgesehen. Welche Varianten für Ihr Fahrzeug passen, klären wir beim Test.'],
  ['Brauche ich dafür selbst Videoaufnahmen?', 'Nicht zwingend. Der Prozess kann mit vorhandenen Fahrzeugbildern beginnen. Qualität und mögliche Perspektiven hängen vom bereitgestellten Material ab; für bestimmte Ergebnisse können zusätzliche Aufnahmen sinnvoll sein.'],
  ['Kann ich Videos für Instagram, TikTok und YouTube nutzen?', 'Die Ergebnisse können für diese Kanäle in passenden Formaten vorbereitet werden. Prüfen Sie vor der Veröffentlichung die jeweiligen Vorgaben der Plattform.'],
  ['Kann mein Corporate Design eingebaut werden?', 'Ja, vorhandene Farben, Logos und Gestaltungswünsche können für die Video-Erstellung berücksichtigt werden.'],
  ['Kann ich Preise oder Angebote im Video ändern?', 'Bei geänderten Angaben können Sie ein neues Video mit dem aktuellen Angebot erzeugen. Ein bereits exportiertes Video wird nicht nachträglich automatisch geändert.'],
  ['Kann ich verschiedene Video-Stile für dasselbe Fahrzeug erzeugen?', 'Ja. Sie können für dasselbe Fahrzeug verschiedene Stile und Formate wählen; jede neue Erstellung ist ein eigener Vorgang.'],
];

function VideoFrame({ title, ratio = 'aspect-video', label, position = 'object-center', className = '' }: { title: string; ratio?: string; label: string; position?: string; className?: string }) {
  return <div className={`video-concept-frame group relative min-w-0 overflow-hidden rounded-md bg-foreground ${ratio} ${className}`} role="img" aria-label={`Gestaltungsbeispiel: ${title}, ${label}`}>
    <img src={carImage} alt="" loading="lazy" className={`video-concept-image h-full w-full object-cover ${position}`} />
    <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-foreground/90 via-foreground/35 to-transparent px-3 pb-3 pt-10 text-background">
      <p className="font-display text-sm font-bold leading-tight">{label}</p><p className="mt-1 text-[10px] text-background/85">{title} · Beispielvorschau</p>
    </div>
    <span className="absolute left-1/2 top-1/2 flex h-10 w-10 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-background/70 bg-foreground/55 text-background shadow-elevated" aria-hidden="true"><Play className="ml-0.5 h-4 w-4 fill-current" /></span>
    <span className="absolute left-3 top-3 rounded bg-foreground/70 px-1.5 py-1 text-[10px] font-bold text-background">VIDEO · KONZEPT</span>
    <span className="absolute inset-x-0 bottom-0 h-0.5 bg-background/50" aria-hidden="true"><span className="video-concept-progress block h-full w-1/3 bg-accent" /></span>
  </div>;
}

export default function AutohausVideos() {
  usePageMeta({ title: 'Fahrzeugvideos für Autohäuser | autohaus.ai', description: 'Werden Sie Ihr eigener Videograf: Aus Fahrzeugbildern und Daten professionelle Video-Inhalte für Social Media, YouTube und Werbung erstellen.', canonicalPath: '/autohaus-videos' });
  useEffect(() => { captureAttribution('lp_videos'); captureLastTouch(); }, []);
  useEffect(() => {
    const sent = new Set<number>();
    const onScroll = () => { const max = document.documentElement.scrollHeight - window.innerHeight; if (max <= 0) return; const percent = window.scrollY / max * 100; for (const t of [50, 90]) if (percent >= t && !sent.has(t)) { sent.add(t); trackFunnelEvent('scroll_depth', { step: `scroll_${t}`, percent: t }); } };
    window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll);
  }, []);
  return <FunnelLayout ctaHref={TEST_URL} ctaLabel="Video testen" anchors={[{href:'#ablauf',label:"So funktioniert's"},{href:'#videoarten',label:'Videoarten'},{href:'#kanaele',label:'Kanäle'},{href:'#fragen',label:'Fragen'}]}>
    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[.88fr_1.12fr] lg:py-16">
      <div className="min-w-0"><p className="text-xs font-bold uppercase text-accent">Für Autohäuser &amp; Fahrzeughändler</p><h1 className="mt-4 font-display text-4xl font-bold leading-[1.05] sm:text-5xl">Ihr Fahrzeug verdient mehr als ein Standbild.</h1><p className="mt-4 font-display text-xl font-bold text-accent">Werden Sie Ihr eigener Videograf.</p><p className="mt-5 text-sm leading-7 text-muted-foreground sm:text-base">Erstellen Sie professionelle Fahrzeugvideos für Instagram, TikTok, YouTube und Werbeanzeigen. Ohne Videoteam, ohne Schnittprogramm und ohne aufwendige Produktion.</p><div className="mt-7 flex flex-col items-start gap-3"><Button asChild size="lg" className="w-full shadow-glow sm:w-auto"><Link to={TEST_URL} data-cta="videos_test">Video für ein Fahrzeug testen <ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline" size="lg" className="w-full sm:w-auto"><a href="#videoarten">Beispiele ansehen <ChevronRight className="h-4 w-4" /></a></Button></div><p className="mt-5 text-xs text-muted-foreground">Social Media · Ads · YouTube · Hochformat · Querformat</p></div>
      <div className="min-w-0"><div className="grid grid-cols-5 items-center gap-2 sm:gap-3"><div className="col-span-3"><VideoFrame title="YouTube · 16:9" label="Das Fahrzeug im Mittelpunkt" /></div><div className="col-span-2 row-span-2"><VideoFrame title="Reel · 9:16" label="Ein Blick genügt" ratio="aspect-[9/16]" position="object-left" /></div><div className="col-span-3"><VideoFrame title="Video Ad · 16:9" label="Ihr Angebot bewegt" /></div><div className="col-span-2"><VideoFrame title="YouTube Short · 9:16" label="Fahrzeug-Highlight" ratio="aspect-[9/16]" position="object-right" /></div><div className="col-span-3"><VideoFrame title="Kurzclip · 9:16" label="Neues im Bestand" ratio="aspect-[4/5]" /></div></div><p className="mt-2 text-[11px] text-muted-foreground">Gestaltungsbeispiele mit Ihrem Fahrzeug · keine abspielbaren Beispielvideos</p></div>
    </div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Ein Video ist schnell geplant. Die Produktion nicht.</h2><ol className="mt-7 flex gap-2 overflow-x-auto pb-3 [scrollbar-width:thin]">{classicLine.map((t,i)=><li key={t} className="flex shrink-0 items-center gap-2"><span className="rounded-md border border-border bg-card px-3 py-2 text-xs font-semibold"><span className="mr-2 text-accent">{String(i+1).padStart(2,'0')}</span>{t}</span>{i<classicLine.length-1&&<ChevronRight className="h-4 w-4 text-muted-foreground" />}</li>)}</ol><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{problems.map(({icon:Icon,title,text})=><div key={title} className="rounded-lg border border-border bg-card p-5 shadow-card"><Icon className="h-6 w-6 text-accent"/><h3 className="mt-4 font-display font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div><p className="mt-7 font-display text-2xl font-bold">Das Fahrzeug ist da. Der Content fehlt.</p></div></section>
    <section id="ablauf" className="scroll-mt-20 border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Vom Fahrzeug zum Video.</h2><div className="relative mt-7 grid gap-5 lg:grid-cols-2 lg:gap-12"><div className="rounded-lg border border-destructive/25 bg-secondary/35 p-6"><h3 className="flex items-center gap-3 font-display text-xl font-bold"><X className="h-6 w-6 text-destructive"/>Der klassische Weg</h3><ol className="mt-5 grid gap-2 sm:grid-cols-2">{classic.map((t,i)=><li key={t} className="flex gap-2 text-sm"><span className="w-5 shrink-0 text-right text-xs text-muted-foreground">{i+1}.</span>{t}</li>)}</ol></div><span className="absolute left-1/2 top-1/2 hidden h-11 w-11 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-accent text-accent-foreground shadow-glow lg:flex" aria-hidden="true"><ArrowRight className="h-5 w-5"/></span><div className="rounded-lg border-2 border-accent/45 bg-secondary/35 p-6"><h3 className="flex items-center gap-3 font-display text-xl font-bold"><Check className="h-6 w-6 text-accent"/>Mit autohaus.ai</h3><ol className="mt-6 space-y-6">{short.map(([t,d],i)=><li key={t} className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-accent font-bold text-accent-foreground">{i+1}</span><div><p className="font-display font-bold">{t}</p><p className="mt-1 text-sm text-muted-foreground">{d}</p></div></li>)}</ol></div></div><div className="mt-6 flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase text-muted-foreground">Fällt weg:</span>{['Drehtermin','Kamerateam','Schnittprogramm','manueller Export','mehrfache Formatanpassung'].map(t=><span key={t} className="flex items-center gap-1 rounded-full border border-border bg-secondary/50 px-3 py-1.5 text-xs text-muted-foreground line-through"><X className="h-3 w-3 text-destructive"/>{t}</span>)}</div></div></section>
    <section className="border-b border-border bg-card py-16 sm:py-20"><div className="mx-auto max-w-4xl px-4 text-center sm:px-6"><p className="font-display text-3xl font-bold leading-tight sm:text-5xl">Nicht jedes Fahrzeug braucht einen Drehtag.</p><p className="mt-5 text-base text-accent sm:text-xl">Aber jedes Fahrzeug kann professionell in Bewegung gebracht werden.</p></div></section>
    <section id="videoarten" className="scroll-mt-20 border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="text-xs font-bold uppercase text-accent">Videobeispiele</p><h2 className="mt-2 font-display text-3xl font-bold">Ein Fahrzeug. Viele Geschichten.</h2><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Wählen Sie die Erzählweise, die zu Ihrem Fahrzeug und Ihrer Kampagne passt.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{videoKinds.map(({name,desc,ratio,tag,position,icon:Icon})=><article key={name} className="min-w-0 rounded-lg border border-border bg-card p-3 shadow-card"><VideoFrame title={name} label={tag} ratio={ratio} position={position} className="max-h-72"/><div className="flex items-start gap-3 p-2 pt-4"><Icon className="h-5 w-5 shrink-0 text-accent"/><div><h3 className="font-display font-bold">{name}</h3><p className="mt-1 text-sm text-muted-foreground">{desc}</p></div></div></article>)}</div><p className="mt-3 text-xs text-muted-foreground">Konzeptionelle Vorschauen, keine abspielbaren Videos. Ergebnisse hängen vom Ausgangsmaterial ab.</p></div></section>
    <section id="kanaele" className="scroll-mt-20 border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Posten, wo Ihre Kunden scrollen.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{channels.map(({name,text,format})=><div key={name} className="rounded-lg border border-border bg-secondary/40 p-5"><div className="flex items-center justify-between"><MonitorPlay className="h-6 w-6 text-accent"/><span className="text-xs text-muted-foreground">{format}</span></div><h3 className="mt-5 font-display text-lg font-bold">{name}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div><p className="mt-7 font-display text-xl font-bold">Ein Ausgangsmaterial. Mehrere Formate. Unterschiedliche Plattformen.</p></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Machen Sie aus einem Fahrzeug etwas, das auffällt.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Aus demselben Fahrzeug können unterschiedliche visuelle Geschichten entstehen, passend zu Marke, Modell und Kampagne.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{styles.map((t,i)=><div key={t} className="relative min-w-0 overflow-hidden rounded-lg border border-border bg-card shadow-card"><img src={carImage} alt="" loading="lazy" className={`aspect-[4/3] w-full object-cover ${i%3===0?'object-left':i%3===1?'object-center':'object-right'}`}/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-foreground/85 to-transparent px-3 pb-3 pt-7 text-background"><p className="font-display text-sm font-bold">{t}</p></div></div>)}</div><p className="mt-3 text-xs text-muted-foreground">Stilrichtungen als illustrative Vorschau, keine fertigen Videodateien.</p></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Professioneller Video-Content. Ohne Produktionsapparat.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(({icon:Icon,title,text})=><div key={title} className="rounded-lg border border-border bg-secondary/40 p-5"><Icon className="h-6 w-6 text-accent"/><h3 className="mt-4 font-display font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div><div className="mt-4 flex gap-4 rounded-lg border border-accent/30 bg-accent/5 p-5"><RefreshCw className="h-6 w-6 shrink-0 text-accent"/><div><h3 className="font-display font-bold">Aktionen schneller aktualisieren</h3><p className="mt-1 text-sm text-muted-foreground">Neuer Preis, neue Rate, neues Modell? Ein neues Video erstellen statt einen neuen Dreh organisieren.</p></div></div></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="text-xs font-bold uppercase text-accent">Typischer Alltag</p><h2 className="mt-2 font-display text-3xl font-bold">Ein Fahrzeug kommt heute rein. Morgen soll es auf Social Media laufen.</h2><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="rounded-lg border border-destructive/25 bg-card p-6"><h3 className="font-display text-lg font-bold">Klassisch</h3><ul className="mt-4 space-y-2">{['Videograf anfragen','Termin finden','Fahrzeug vorbereiten','Drehen','Schneiden','Freigeben'].map(t=><li key={t} className="flex gap-2 text-sm"><X className="h-4 w-4 shrink-0 text-destructive"/>{t}</li>)}</ul></div><div className="rounded-lg border-2 border-accent/40 bg-card p-6"><h3 className="font-display text-lg font-bold">Mit autohaus.ai</h3><ol className="mt-4 space-y-3">{['Fahrzeug auswählen','Stil wählen','Video erzeugen','Veröffentlichen'].map((t,i)=><li key={t} className="flex items-center gap-3 text-sm"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent text-xs font-bold text-accent-foreground">{i+1}</span>{t}</li>)}</ol></div></div><p className="mt-4 text-xs text-muted-foreground">Ablaufvergleich, keine Zusage für eine bestimmte Fertigstellungszeit.</p></div></section>
    <section className="border-b border-border bg-card py-14"><div className="mx-auto max-w-3xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">Video muss nicht jedes Mal eine eigene Produktion sein.</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Professionelle Fahrzeugvideos sind klassisch mit Kamera, Schnitt und Personal verbunden. autohaus.ai macht wiederkehrenden Video-Content deutlich einfacher.</p></div></section>
    <section className="border-b border-border bg-secondary/45 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="font-display text-3xl font-bold">So testen Sie autohaus.ai</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[['Fahrzeugbild hochladen','Laden Sie ein Bild aus Ihrem Bestand für die Testanfrage hoch.'],['Einsatzziel nennen','Video als Ziel auswählen und Stil oder Format im optionalen Notizfeld angeben.'],['Ergebnis ansehen','Sie erhalten ein Ergebnis für Ihr Fahrzeug; die Video-Möglichkeiten klären wir anschließend schriftlich.']].map(([title,text],i)=><div key={title} className="rounded-lg border border-border bg-card p-5"><span className="font-display text-2xl font-bold text-accent">0{i+1}</span><h3 className="mt-3 font-display font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground">{['Nur für Unternehmer','Testmaterial wird nicht veröffentlicht','Datenschutz im bestehenden Testprozess','Schriftliche Rückmeldung'].map(t=><p key={t} className="flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-accent"/>{t}</p>)}</div></div></section>
    <section id="fragen" className="scroll-mt-20 border-b border-border bg-secondary/45 py-14"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase text-accent">Häufige Fragen</p><h2 className="mt-2 font-display text-3xl font-bold">Noch Fragen?</h2><p className="mt-3 text-sm text-muted-foreground">Kurze Antworten zu Material, Formaten und Video-Stilen.</p></div><Accordion type="single" collapsible className="space-y-3">{faq.map(([q,a],i)=><AccordionItem key={q} value={`faq-${i}`} className="rounded-lg border border-border bg-card px-5 shadow-card last:border-b"><AccordionTrigger className="text-left text-sm font-semibold hover:no-underline">{q}</AccordionTrigger><AccordionContent className="text-sm leading-6 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="px-4 py-14 sm:px-6"><div className="gradient-hero mx-auto max-w-6xl rounded-lg px-6 py-10 text-primary-foreground sm:px-10 sm:py-14"><h2 className="font-display text-3xl font-bold leading-tight sm:text-4xl">Ihr nächstes Fahrzeug kann mehr als nur fotografiert werden.</h2><p className="mt-2 font-display text-xl font-bold">Bringen Sie es in Bewegung.</p><p className="mt-4 max-w-2xl text-sm leading-6 text-primary-foreground/85">Erstellen Sie Ihr erstes Fahrzeugvideo mit autohaus.ai und sehen Sie, wie Ihr Bestand für Social Media, YouTube und Werbung wirken kann.</p><Button asChild size="lg" variant="secondary" className="mt-6 w-full sm:w-auto"><Link to={TEST_URL} data-cta="videos_test">Video für ein Fahrzeug testen <ArrowRight className="h-4 w-4"/></Link></Button><p className="mt-3 text-xs text-primary-foreground/80">Instagram · TikTok · YouTube · Ads</p></div></section>
  </FunnelLayout>;
}
