/**
 * WMI 2-character prefix → brand (less specific, fallback)
 */
export const WMI2_DATA: Record<string, string> = {
  JA: 'Isuzu',
  JF: 'Subaru',
  JH: 'Honda',
  JM: 'Mazda',
  JN: 'Nissan',
  JS: 'Suzuki',
  JT: 'Toyota',
  KL: 'Daewoo',
  KM: 'Hyundai',
  KN: 'Kia',
  UU: 'Dacia',
  '1C': 'Chrysler',
  '1D': 'Dodge',
  '1F': 'Ford',
  '1G': 'General Motors',
  '1H': 'Honda',
  '1J': 'Jeep',
  '1L': 'Lincoln',
  '1N': 'Nissan',
  '2F': 'Ford',
  '2G': 'General Motors',
  '2H': 'Hyundai',
  '2M': 'Mercury',
  '2T': 'Toyota',
  '3F': 'Ford',
  '3G': 'General Motors',
  '3H': 'Honda',
  '3N': 'Nissan',
  '3V': 'Volkswagen',
  '4F': 'Mazda',
  '4M': 'Mercury',
  '4S': 'Subaru',
  '4T': 'Toyota',
  '4U': 'BMW',
  '5F': 'Honda',
  '5J': 'Honda',
  '5L': 'Lincoln',
  '5N': 'Hyundai',
  '5T': 'Hyundai',
  '5X': 'Kia',
  '5Y': 'Tesla',
  '6F': 'Ford',
  '6H': 'Holden',
  '6T': 'Toyota',
};
