/**
 * WMI 3-character codes → brand name
 * Auto-generated from Wikibooks WMI list
 */
export const WMI3_DATA: Record<string, string> = {
  // ══════════════════════════════════════
  // === Africa ===
  // ══════════════════════════════════════
  AAA: 'Audi',
  AAK: 'FAW',
  AAM: 'MAN',
  AAP: 'SAPVIN',
  AAV: 'Volkswagen',
  AAW: 'Challenger Trailer',
  ABJ: 'Mitsubishi',
  ABM: 'BMW',
  ACV: 'Isuzu',
  AC5: 'Hyundai',
  ADB: 'Mercedes-Benz',
  ADD: 'UD Trucks',
  ADM: 'General Motors',
  ADN: 'Nissan',
  ADR: 'Renault',
  ADX: 'Tata',
  AFA: 'Ford',
  AFB: 'Mazda',
  AFD: 'BAIC',
  AFZ: 'Fiat',
  AHH: 'Hino',
  AHM: 'Honda',
  AHT: 'Toyota',
  BR1: 'Mercedes-Benz',
  BRY: 'Fiat',
  BUK: 'Kiira Motors',
  CA3: 'MCV',
  DDY: 'Geyushi Motors',

  // ══════════════════════════════════════
  // === Russia ===
  // ══════════════════════════════════════
  EAA: 'Aurus',
  EAN: 'Evolute',
  EAU: 'EVM',
  EBE: 'Sollers',
  EBZ: 'Nizhekotrans',
  ECE: 'XCITE',
  ECW: 'Trans-Alfa',

  // ══════════════════════════════════════
  // === China (H) ===
  // ══════════════════════════════════════
  HA0: 'Sundiro',
  HA6: 'Niu',
  HA7: 'Qingqi',
  HES: 'Smart',
  HGL: 'Farizon',
  HGX: 'Wuling',
  HHZ: 'Huazi',
  HJN: 'Firefly',
  HJR: 'Jetour',
  HJZ: 'Juzhen',
  HJ4: 'BAW',
  HL4: 'Moto Morini',
  HLX: 'Li Auto',
  HRV: 'Henrey',
  HVW: 'Volkswagen',
  HWM: 'Weltmeister',
  HXM: 'Xiaomi',
  HZ2: 'Zhilong',
  H0D: 'Qianxin',
  H0G: 'Wisdom',

  // ══════════════════════════════════════
  // === Japan (J) ===
  // ══════════════════════════════════════
  JAA: 'Isuzu',
  JAB: 'Isuzu',
  JAC: 'Isuzu',
  JAE: 'Acura',
  JAL: 'Isuzu',
  JAM: 'Isuzu',
  JA3: 'Mitsubishi',
  JA4: 'Mitsubishi',
  JA7: 'Mitsubishi',
  JB3: 'Dodge',
  JB4: 'Dodge',
  JB7: 'Dodge',
  JC0: 'Mazda',
  JC1: 'Fiat',
  JC2: 'Mazda',
  JDA: 'Daihatsu',
  JD1: 'Daihatsu',
  JD2: 'Daihatsu',
  JD4: 'Daihatsu',
  JE3: 'Mitsubishi',
  JE4: 'Mitsubishi',
  JF1: 'Subaru',
  JF2: 'Subaru',
  JF3: 'Subaru',
  JF4: 'Subaru',
  JG1: 'Chevrolet',
  JG2: 'Pontiac',
  JG7: 'Pontiac',
  JGC: 'Chevrolet',
  JGT: 'GMC',
  JHA: 'Hino',
  JHB: 'Hino',
  JHD: 'Hino',
  JHF: 'Hino',
  JHH: 'Hino',
  JHL: 'Honda',
  JHM: 'Honda',
  JH1: 'Honda',
  JH2: 'Honda',
  JH3: 'Honda',
  JH4: 'Acura',
  JH6: 'Hino',
  JJ3: 'Chrysler',
  JKA: 'Kawasaki',
  JKB: 'Kawasaki',
  JKM: 'Mitsuoka',
  JKS: 'Suzuki',
  JK8: 'Suzuki',
  JLB: 'Mitsubishi Fuso',
  JLF: 'Mitsubishi Fuso',
  JLS: 'Sterling',
  JL5: 'Mitsubishi Fuso',
  JL6: 'Mitsubishi Fuso',
  JL7: 'Mitsubishi Fuso',
  JMA: 'Mitsubishi',
  JMB: 'Mitsubishi',
  JMF: 'Mitsubishi',
  JMP: 'Mitsubishi',
  JMR: 'Mitsubishi',
  JMY: 'Mitsubishi',
  JMZ: 'Mazda',
  JM0: 'Mazda',
  JM1: 'Mazda',
  JM2: 'Mazda',
  JM3: 'Mazda',
  JM4: 'Mazda',
  JM6: 'Mazda',
  JM7: 'Mazda',
  JNA: 'UD Trucks',
  JNC: 'UD Trucks',
  JNE: 'UD Trucks',
  JNK: 'Infiniti',
  JNR: 'Infiniti',
  JNX: 'Infiniti',
  JN1: 'Nissan',
  JN3: 'Nissan',
  JN6: 'Nissan',
  JN8: 'Nissan',
  JPC: 'UD Trucks',
  JP3: 'Plymouth',
  JP4: 'Plymouth',
  JP7: 'Plymouth',
  JR2: 'Isuzu',
  JSA: 'Suzuki',
  JSK: 'Kawasaki',
  JSL: 'Kawasaki',
  JST: 'Suzuki',
  JS1: 'Suzuki',
  JS2: 'Suzuki',
  JS3: 'Suzuki',
  JS4: 'Suzuki',
  JTB: 'Toyota',
  JTD: 'Toyota',
  JTE: 'Toyota',
  JTF: 'Toyota',
  JTG: 'Toyota',
  JTH: 'Lexus',
  JTJ: 'Lexus',
  JTK: 'Toyota',
  JTL: 'Toyota',
  JTM: 'Toyota',
  JTN: 'Toyota',
  JTP: 'Toyota',
  JT1: 'Toyota',
  JT2: 'Toyota',
  JT3: 'Toyota',
  JT4: 'Toyota',
  JT5: 'Toyota',
  JT6: 'Lexus',
  JT7: 'Toyota',
  JT8: 'Lexus',
  JW6: 'Mitsubishi Fuso',
  JYA: 'Yamaha',
  JYE: 'Yamaha',
  JY3: 'Yamaha',
  JY4: 'Yamaha',
  J81: 'Chevrolet',
  J87: 'Pontiac',
  J8B: 'Chevrolet',
  J8C: 'Chevrolet',
  J8D: 'GMC',
  J8T: 'GMC',
  J8Z: 'Chevrolet',

  // ══════════════════════════════════════
  // === South Korea (K) ===
  // ══════════════════════════════════════
  KF3: 'Merkavim',
  KF6: 'Automotive Industries',
  KLA: 'Daewoo',
  KLP: 'CT&T',
  KLT: 'Tata Daewoo',
  KLU: 'Tata Daewoo',
  KLY: 'Daewoo',
  KL1: 'Chevrolet',
  KL2: 'Pontiac',
  KL3: 'Holden',
  KL4: 'Buick',
  KL5: 'Suzuki',
  KL6: 'GMC',
  KL7: 'Chevrolet',
  KL8: 'Chevrolet',
  KMC: 'Hyundai',
  KME: 'Hyundai',
  KMF: 'Hyundai',
  KMH: 'Hyundai',
  KMJ: 'Hyundai',
  KMT: 'Genesis',
  KMU: 'Genesis',
  KMX: 'Hyundai',
  KMY: 'Daelim',
  KM1: 'Hyosung',
  KM4: 'Hyosung',
  KM8: 'Hyundai',
  KNA: 'Kia',
  KNC: 'Kia',
  KND: 'Kia',
  KNE: 'Kia',
  KNF: 'Kia',
  KNG: 'Kia',
  KNJ: 'Kia',
  KNM: 'Renault',
  KN1: 'Asia Motors',
  KN2: 'Asia Motors',
  KPA: 'SsangYong',
  KPB: 'SsangYong',
  KPD: 'SsangYong',
  KPH: 'Mitsubishi',
  KPT: 'SsangYong',

  // ══════════════════════════════════════
  // === China (L) ===
  // ══════════════════════════════════════
  LAA: 'Jialing',
  LAE: 'Qingqi',
  LAL: 'Sundiro Honda',
  LAN: 'Yamasaki',
  LAP: 'Jianshe',
  LAT: 'Dayang',
  LA6: 'King Long',
  LA7: 'Radar Auto',
  LA8: 'Ankai',
  LBB: 'Qianjiang',
  LBE: 'Hyundai',
  LBM: 'Zongshen Piaggio',
  LBP: 'Yamaha',
  LBV: 'BMW',
  LBX: 'Kinroad',
  LBZ: 'Yeksan',
  LB1: 'Mercedes-Benz',
  LB2: 'Geely',
  LB3: 'Geely',
  LB4: 'Yinxiang',
  LB5: 'Fosti',
  LB7: 'New Summit',
  LCE: 'CFMOTO',
  LCR: 'Gonow',
  LC0: 'BYD',
  LC2: 'Kymco',
  LC6: 'Suzuki',
  LDB: 'Dadi',
  LDC: 'Peugeot',
  LDD: 'Huanghai',
  LDF: 'Fulu',
  LDK: 'FAW Bus',
  LDN: 'Mitsubishi',
  LDP: 'Dongfeng',
  LDY: 'Zhongtong',
  LD3: 'Zontes',
  LD5: 'Benzhou',
  LEC: 'Qingyuan',
  LEF: 'JMC',
  LEH: 'Riya',
  LET: 'Isuzu',
  LEW: 'Dongfeng',
  LE4: 'Mercedes-Benz',
  LE8: 'Hua\'Nan',
  LFB: 'Hongqi',
  LFF: 'Wangye',
  LFG: 'Chuanl',
  LFJ: 'Keyton',
  LFM: 'Toyota',
  LFN: 'FAW Bus',
  LFP: 'Bestune',
  LFT: 'FAW',
  LFU: 'Lifeng',
  LFV: 'Volkswagen',
  LFW: 'FAW',
  LFX: 'Sany',
  LFY: 'Changshu',
  LFZ: 'Leapmotor',
  LF3: 'Lifan',
  LGA: 'Dongfeng',
  LGB: 'Nissan',
  LGC: 'Dongfeng',
  LGF: 'Dongfeng',
  LGG: 'Forthing',
  LGJ: 'Dongfeng',
  LGL: 'Guilin Daewoo',
  LGV: 'Guoji Nanlian',
  LGW: 'Great Wall',
  LGX: 'BYD',
  LGZ: 'Denway',
  LG6: 'Dayun',
  LHA: 'Shuanghuan',
  LHB: 'BAIC',
  LHG: 'Honda',
  LHJ: 'Bashan',
  LHM: 'Dongfeng Renault',
  LHW: 'CRRC',
  LH0: 'Weltmeister',
  LH1: 'FAW-Haima',
  LJC: 'Jincheng',
  LJD: 'Kia',
  LJM: 'Sunlong',
  LJN: 'Zhengzhou Nissan',
  LJR: 'CIMC',
  LJS: 'Yaxing',
  LJU: 'Lotus',
  LJV: 'Sinotruk',
  LJW: 'Landwind',
  LJX: 'JMC Ford',
  LJ1: 'Nio',
  LJ4: 'Jmstar',
  LJ5: 'Jinlun',
  LJ8: 'Zotye',
  LKC: 'BAIC',
  LKG: 'Youngman',
  LKH: 'Hafei',
  LKL: 'Higer Bus',
  LKT: 'Lifan Junma',
  LK2: 'JAC Bus',
  LK6: 'Wuling',
  LK8: 'Yule',
  LLC: 'Loncin',
  LLJ: 'Xinling',
  LLN: 'Qoros',
  LLP: 'Jiajue',
  LLU: 'Dongfeng',
  LLV: 'Lifan',
  LLX: 'Yudo',
  LL0: 'Yongfu',
  LL2: 'Weltmeister',
  LL3: 'Golden Dragon',
  LL6: 'GAC Mitsubishi',
  LL8: 'Yamaha',
  LMC: 'Suzuki',
  LME: 'Skyworth',
  LMF: 'Zhongyu',
  LMG: 'GAC',
  LMH: 'Motoleader',
  LMP: 'Geely',
  LMV: 'Haima',
  LMW: 'GAC',
  LMX: 'Forthing',
  LM0: 'Wangye',
  LM6: 'SWM',
  LM8: 'Seres',
  LNA: 'GAC',
  LNB: 'BAIC',
  LND: 'JMEV',
  LNE: 'CRRC',
  LNN: 'Chery',
  LNP: 'MG',
  LNV: 'Naveco',
  LNX: 'Dongfeng',
  LNY: 'Yuejin',
  LPA: 'DS',
  LPE: 'BYD',
  LPS: 'Polestar',
  LP6: 'Haojian',
  LRB: 'Buick',
  LRD: 'Foton Daimler',
  LRE: 'Cadillac',
  LRP: 'Rato',
  LRR: 'Longjia',
  LRW: 'Tesla',
  LR4: 'Yadi',
  LR6: 'Dayun',
  LSC: 'Changan',
  LSF: 'SAIC',
  LSG: 'Chevrolet',
  LSH: 'SAIC Maxus',
  LSJ: 'MG',
  LSK: 'SAIC Maxus',
  LSV: 'Volkswagen',
  LSY: 'Brilliance',
  LS3: 'Hejia',
  LS4: 'Changan',
  LS5: 'Changan',
  LS6: 'Changan',
  LS7: 'JMC',
  LS8: 'Shaolin',
  LTA: 'ZX Auto',
  LTN: 'Soueast',
  LTP: 'NEVS',
  LTV: 'Toyota',
  LTW: 'Enovate',
  LT1: 'Tonghua',
  LUC: 'Honda',
  LUD: 'Dongfeng Nissan Diesel',
  LUG: 'Qiantu',
  LUJ: 'Shanqi Tianying',
  LUR: 'Chery',
  LUX: 'Dongfeng Yulon',
  LUZ: 'Neta',
  LVA: 'Foton',
  LVB: 'Foton',
  LVC: 'Foton',
  LVF: 'Changhe Suzuki',
  LVG: 'Toyota',
  LVH: 'Honda',
  LVM: 'Chery',
  LVP: 'DFSK',
  LVR: 'Mazda',
  LVS: 'Ford',
  LVT: 'Chery',
  LVU: 'Jetour',
  LVV: 'Chery',
  LVX: 'Aiways',
  LVY: 'Volvo',
  LVZ: 'DFSK',
  LV3: 'Hengchi',
  LV7: 'Qingqi',
  LWB: 'Wuyang Honda',
  LWE: 'Yangtse',
  LWG: 'Huansong',
  LWL: 'Qingling Isuzu',
  LWM: 'Wonjan',
  LWV: 'Jeep',
  LWX: 'Wanxiang',
  LW4: 'Li Auto',
  LXA: 'Qipai',
  LXD: 'Dongfang Lingyun',
  LXG: 'XCMG',
  LXK: 'Meitian',
  LXM: 'SYM',
  LXN: 'Link Tour',
  LXV: 'Borgward',
  LXW: 'JMC Ford',
  LXY: 'Shineray',
  LX6: 'Huari',
  LX8: 'Xgjao',
  LYB: 'Yaxing',
  LYD: 'Kaitong',
  LYJ: 'ZhongdaYanjing',
  LYM: 'Yamaha',
  LYS: 'Vmoto',
  LYU: 'Huansu',
  LYV: 'Volvo',
  LY4: 'Yingang',
  LZE: 'Isuzu',
  LZF: 'SAIC Hongyan',
  LZG: 'Shacman',
  LZK: 'Sinotruk',
  LZL: 'Haili',
  LZM: 'MAN',
  LZP: 'Baotian',
  LZS: 'Zongshen',
  LZU: 'Isuzu',
  LZW: 'Wuling',
  LZY: 'Yutong',
  LZZ: 'Sinotruk',
  LZ0: 'Wuzheng',
  LZ4: 'Linzhi',
  L1K: 'Hengtong',
  L1N: 'XPeng',
  L10: 'Geely Emgrand',
  L2B: 'Baodiao',
  L2C: 'Jaguar',
  L3H: 'Victory',
  L37: 'Zhenhua',
  L4B: 'Xingyue',
  L4F: 'Eagle Electric',
  L4H: 'Longjia',
  L4S: 'Xingyue',
  L4Y: 'Qingqi Rhon',
  L5C: 'Kangdi',
  L5E: 'Zoomlion',
  L5K: 'Yongkang Easy',
  L5N: 'Taotao',
  L5Y: 'Znen',
  L6F: 'Liangzi',
  L6J: 'Kayo',
  L6K: 'Howhit',
  L6T: 'Geely',
  L66: 'Granton',
  L82: 'Baotian',
  L85: 'Huabao',
  L8A: 'Youngman',
  L8X: 'Summit',
  L8Y: 'Jonway',
  L9G: 'Guangtong',
  L9N: 'Taotao',

  // ══════════════════════════════════════
  // === India (M) ===
  // ══════════════════════════════════════
  MAA: 'Kawasaki',
  MAB: 'Mahindra',
  MAC: 'Mahindra',
  MAH: 'Fiat',
  MAJ: 'Ford',
  MAK: 'Honda',
  MAL: 'Hyundai',
  MAN: 'Eicher',
  MAT: 'Tata',
  MA1: 'Mahindra',
  MA3: 'Suzuki',
  MA6: 'General Motors',
  MA7: 'Hindustan Motors',
  MA8: 'Daewoo',
  MBF: 'Royal Enfield',
  MBH: 'Suzuki',
  MBJ: 'Toyota',
  MBK: 'MAN',
  MBL: 'Hero MotoCorp',
  MBR: 'Mercedes-Benz',
  MBU: 'Swaraj',
  MBV: 'Premier',
  MBX: 'Piaggio',
  MBY: 'Asia Motor Works',
  MB1: 'Ashok Leyland',
  MB2: 'Hyundai',
  MB7: 'Mahindra Reva',
  MB8: 'Suzuki',
  MCA: 'Fiat',
  MCB: 'General Motors',
  MCD: 'Mahindra',
  MCG: 'Atul Auto',
  MCL: 'International Cars',
  MC1: 'Force Motors',
  MC2: 'Eicher',
  MC4: 'Dilip Chhabria',
  MDE: 'Kinetic',
  MDH: 'Nissan',
  MDT: 'Kerala Automobiles',
  MD2: 'KTM',
  MD6: 'TVS',
  MD7: 'LML',
  MD9: 'Shuttle Cars',
  MEC: 'BharatBenz',
  MEE: 'Renault',
  MEG: 'Harley-Davidson',
  MER: 'Benelli',
  MES: 'Mahindra Navistar',
  MET: 'Piaggio',
  MEX: 'Škoda',
  ME1: 'Yamaha',
  ME3: 'Royal Enfield',
  ME4: 'Honda',
  MYH: 'Ather Energy',
  MZB: 'Kia',
  MZD: 'Jawa',
  MZZ: 'Citroën',
  MZ7: 'MG',
  M3G: 'Isuzu',
  M6F: 'UM Lohia',

  // ══════════════════════════════════════
  // === Indonesia (MH) ===
  // ══════════════════════════════════════
  MF3: 'Hyundai',
  MHD: 'Suzuki',
  MHF: 'Toyota',
  MHK: 'Daihatsu',
  MHL: 'Mercedes-Benz',
  MHR: 'Honda',
  MHY: 'Suzuki',
  MH1: 'Honda',
  MH3: 'Yamaha',
  MH4: 'Kawasaki',
  MH8: 'Suzuki',
  MJB: 'General Motors',
  MKF: 'DFSK',
  MK2: 'Mitsubishi',
  MK3: 'Wuling',

  // ══════════════════════════════════════
  // === Thailand (ML/MM/MN/MP/MR) ===
  // ══════════════════════════════════════
  MLB: 'Yamaha',
  MLC: 'Suzuki',
  MLE: 'Yamaha',
  MLH: 'Honda',
  MLW: 'Sco Motor',
  MLY: 'Harley-Davidson',
  ML0: 'Ducati',
  ML3: 'Mitsubishi',
  ML5: 'Kawasaki',
  MMA: 'Mitsubishi',
  MMB: 'Mitsubishi',
  MMC: 'Mitsubishi',
  MMD: 'Mitsubishi',
  MME: 'Mitsubishi',
  MMF: 'BMW',
  MML: 'MG',
  MMM: 'Chevrolet',
  MMR: 'Subaru',
  MMS: 'Suzuki',
  MMT: 'Mitsubishi',
  MMU: 'Holden',
  MM0: 'Mazda',
  MM6: 'Mazda',
  MM7: 'Mazda',
  MM8: 'Mazda',
  MNA: 'Ford',
  MNB: 'Ford',
  MNC: 'Ford',
  MNK: 'Hino',
  MNT: 'Nissan',
  MNU: 'Great Wall',
  MN3: 'Mitsubishi',
  MPA: 'Isuzu',
  MPB: 'Ford',
  MP1: 'Isuzu',
  MP2: 'Mazda',
  MP3: 'Plymouth',
  MP5: 'Foton',
  MRH: 'Honda',
  MRT: 'Neta',
  MR0: 'Toyota',
  MR1: 'Toyota',
  MR2: 'Toyota',
  MR3: 'Toyota',
  MS0: 'Super Seven Stars',
  MS1: 'Super Seven Stars',
  MS3: 'Suzuki',
  MXB: 'Saryarka',
  MXL: 'Yutong',
  MXV: 'Ural',
  MX3: 'Hyundai',

  // ══════════════════════════════════════
  // === Iran/Pakistan/Turkey (N) ===
  // ══════════════════════════════════════
  NAA: 'Iran Khodro',
  NAC: 'Mammut',
  NAD: 'Škoda',
  NAL: 'Maral',
  NAP: 'Pars Khodro',
  NAS: 'SAIPA',
  NFB: 'Honda',
  NG3: 'Lucky Motor',
  NLA: 'Honda',
  NLC: 'Askam',
  NLE: 'Mercedes-Benz',
  NLF: 'Koluman',
  NLH: 'Hyundai',
  NLJ: 'Hyundai',
  NLN: 'Karsan',
  NLR: 'Otokar',
  NLT: 'Temsa',
  NLZ: 'Tezeller',
  NL1: 'TOGG',
  NL2: 'HABAS',
  NMA: 'MAN',
  NMB: 'Mercedes-Benz',
  NMC: 'BMC',
  NMH: 'Honda',
  NMS: 'Otoyol',
  NMT: 'Toyota',
  NM0: 'Ford',
  NM1: 'Renault',
  NM4: 'Fiat',
  NNA: 'Isuzu',
  NRE: 'Bozankaya',
  NRX: 'Musoshi',
  NRY: 'Pilotcar',
  NSA: 'SamAvto',
  NS2: 'MAN',
  NVA: 'Khazar',

  // ══════════════════════════════════════
  // === Philippines/Malaysia/Singapore (P) ===
  // ══════════════════════════════════════
  PAB: 'Isuzu',
  PAD: 'Honda',
  PE1: 'Ford',
  PE3: 'Mazda',
  PFD: 'Hyundai',
  PL1: 'Proton',
  PL8: 'Hyundai',
  PLP: 'Subaru',
  PLZ: 'Isuzu',
  PMA: 'MAN',
  PMH: 'Honda',
  PMK: 'Honda',
  PML: 'Hicom',
  PMN: 'Modenas',
  PMS: 'Suzuki',
  PMV: 'Yamaha',
  PMY: 'Yamaha',
  PM1: 'BMW',
  PM2: 'Perodua',
  PNA: 'Peugeot',
  PNS: 'SKSBUS',
  PNV: 'Volvo',
  PN1: 'Toyota',
  PN2: 'Toyota',
  PN8: 'Nissan',
  PPP: 'Suzuki',
  PPV: 'Volkswagen',
  PP1: 'Mazda',
  PP3: 'Hyundai',
  PRA: 'Sinotruk',
  PRH: 'Chery',
  PRN: 'GAC',
  PRX: 'Kia',
  PR8: 'Ford',
  PV3: 'Ford',

  // ══════════════════════════════════════
  // === UAE ===
  // ══════════════════════════════════════
  RA1: 'Steyr',

  // ══════════════════════════════════════
  // === Taiwan (RF/RK) ===
  // ══════════════════════════════════════
  RFB: 'Kymco',
  RFC: 'Golden Bee',
  RFD: 'Tai Ling',
  RFG: 'SYM',
  RFL: 'Adly',
  RFT: 'CPI',
  RFV: 'PGO',
  RF3: 'Aeon',
  RF5: 'Luxgen',
  RF8: 'EVT',
  RGS: 'Kawasaki',
  RHA: 'Ford',
  RKJ: 'Prince Motors',
  RKL: 'Toyota',
  RKM: 'China Motor',
  RKR: 'Yamaha',
  RKT: 'Access Motor',
  RK3: 'Honda',
  RK7: 'Kawasaki',

  // ══════════════════════════════════════
  // === Vietnam (RL) ===
  // ══════════════════════════════════════
  RLA: 'Mitsubishi',
  RLC: 'Yamaha',
  RLE: 'Isuzu',
  RLH: 'Honda',
  RLL: 'VinFast',
  RLM: 'Mercedes-Benz',
  RLN: 'VinFast',
  RLV: 'Can-Am',
  RL0: 'Ford',
  RL4: 'Toyota',
  RP8: 'Piaggio',
  RUN: 'Sollers',

  // ══════════════════════════════════════
  // === Hong Kong (R1/R2/R3) ===
  // ══════════════════════════════════════
  R1J: 'Jiayuan',
  R1N: 'Niu',
  R10: 'ZAP',
  R2P: 'Evoke',
  R3M: 'Mangosteen',
  R36: 'Shansu',
  R4N: 'Elyx',
  R82: 'Lantu',

  // ══════════════════════════════════════
  // === Europe – UK (S) ===
  // ══════════════════════════════════════
  SAA: 'Austin',
  SAB: 'Switch Mobility',
  SAD: 'Jaguar',
  SAF: 'ERF',
  SAH: 'Honda',
  SAJ: 'Jaguar',
  SAL: 'Land Rover',
  SAM: 'Morris',
  SAR: 'Rover',
  SAT: 'Triumph',
  SAX: 'Austin-Rover',
  SAY: 'Norton',
  SAZ: 'Freight Rover',
  SA3: 'Ginetta',
  SBB: 'Leyland',
  SBC: 'Iveco Ford',
  SBF: 'Nugent',
  SBJ: 'Leyland Bus',
  SBL: 'Leyland',
  SBM: 'McLaren',
  SBS: 'Scammell',
  SBU: 'United Trailers',
  SBV: 'Kenworth',
  SBW: 'Weightlifter',
  SB1: 'Toyota',
  SCA: 'Rolls-Royce',
  SCB: 'Bentley',
  SCC: 'Lotus',
  SCD: 'Reliant',
  SCE: 'DeLorean',
  SCF: 'Aston Martin',
  SCG: 'Triumph',
  SCK: 'Ifor Williams',
  SCM: 'Grove',
  SCR: 'LEVC',
  SCV: 'Volvo',
  SC5: 'Wrightbus',
  SC6: 'INEOS',
  SDB: 'Talbot',
  SDC: 'SDC Trailers',
  SDF: 'Dodge',
  SDG: 'Renault Trucks',
  SDK: 'Caterham',
  SDL: 'TVR',
  SDP: 'MG',
  SDU: 'Utility',
  SD7: 'Aston Martin',
  SD8: 'Moke',
  SED: 'Opel',
  SEG: 'Dennis Eagle',
  SEP: 'Don-Bur',
  SEY: 'LDV',
  SFA: 'Ford',
  SFD: 'Alexander Dennis',
  SFE: 'Alexander Dennis',
  SFR: 'Fruehauf',
  SFN: 'Foden',
  SFZ: 'Tesla',
  SGA: 'Avondale',
  SGB: 'Bailey',
  SGD: 'Swift',
  SGE: 'Elddis',
  SGL: 'Lunar',
  SG4: 'Coachman',
  SHH: 'Honda',
  SHS: 'Honda',
  SH7: 'INEOS',
  SJA: 'Bentley',
  SJB: 'Brian James',
  SJK: 'Infiniti',
  SJN: 'Nissan',
  SJ1: 'Ree Automotive',
  SKA: 'Vauxhall',
  SKB: 'Kel-Berg',
  SKF: 'Bedford',
  SKL: 'Anaig',
  SLA: 'Rolls-Royce',
  SLC: 'Thwaites',
  SLG: 'McMurtry',
  SLN: 'Niftylift',
  SLP: 'JCB',
  SLV: 'Volvo',
  SMR: 'Montracon',
  SMT: 'Triumph',
  SMW: 'Cartwright',
  SMX: 'Gray & Adams',
  SNE: 'Wartburg',
  SNT: 'Trabant',
  SNZ: 'MZ',
  SPE: 'B-ON',

  // === Europe – Poland (SU/SV/SW/SX/SY/SZ) ===
  SUA: 'Autosan',
  SUB: 'Tramp Trail',
  SUC: 'Wiola',
  SUD: 'Wielton',
  SUF: 'Fiat',
  SUG: 'Mega Trailers',
  SUJ: 'Jelcz',
  SUL: 'FSC',
  SUM: 'Novatrail',
  SUP: 'Daewoo',
  SUU: 'Solaris',
  SVH: 'ZASŁAW',
  SVM: 'Inter Cars',
  SVS: 'BODEX',
  SWH: 'Temared',
  SWR: 'Weekend Trailers',
  SWV: 'TA-NO',
  SWZ: 'Zremb',
  SXE: 'Neptun',
  SXK: 'Konar',
  SXM: 'MELEX',
  SXY: 'Wecon',
  SXX: 'Martz',
  SX7: 'Arthur Bus',
  SYB: 'Rydwan',
  SYG: 'Gniotpol',
  SY1: 'Neso Bus',
  SZA: 'Scania',
  SZC: 'Vectrix',
  SZL: 'Boro',
  SZN: 'Głowacz',
  SZR: 'Niewiadów',
  ST3: 'Calabrese',

  // ══════════════════════════════════════
  // === Europe – Switzerland/Czech/Hungary/Portugal (T) ===
  // ══════════════════════════════════════
  TAW: 'NAW',
  TBS: 'Boschung',
  TCC: 'Smart',
  TDM: 'Quantya',
  TEB: 'Bucher',
  TEM: 'Twike',
  TFH: 'FHS Frech-Hoch',
  TJ5: 'Vezeko',
  TKP: 'Panav',
  TKX: 'Agados',
  TKY: 'Metaco',
  TLJ: 'Jawa',
  TMA: 'Hyundai',
  TMB: 'Škoda',
  TMC: 'Hyundai',
  TMK: 'Karosa',
  TMP: 'Škoda',
  TMT: 'Tatra',
  TNA: 'Avia',
  TNE: 'TAZ',
  TNG: 'LIAZ',
  TNT: 'Tatra',
  TNU: 'Tatra',
  TRA: 'Ikarus',
  TRC: 'Csepel',
  TRE: 'Rákos',
  TRK: 'Credo',
  TRR: 'Rába',
  TRU: 'Audi',
  TSB: 'Ikarus',
  TSE: 'Ikarus',
  TSF: 'Alfabusz',
  TSM: 'Suzuki',
  TSY: 'Keeway',
  TWG: 'CaetanoBus',
  TW0: 'CaetanoBus',
  TW1: 'Toyota',
  TW2: 'Ford',
  TW4: 'UMM',
  TW6: 'Citroën',
  TW7: 'Mini Moke',
  TX5: 'Mini Moke',
  TYA: 'Mitsubishi Fuso',
  TYB: 'Mitsubishi Fuso',
  T3C: 'Lohr',
  T7A: 'Ebusco',

  // ══════════════════════════════════════
  // === Europe – Romania/Denmark/Spain (U) ===
  // ══════════════════════════════════════
  UA1: 'AUSA',
  UA2: 'Iveco',
  UA4: 'Irizar',
  UCY: 'Silence',
  UD3: 'Granalu',
  UHE: 'Scanvogn',
  UHL: 'Camp-let',
  UH2: 'Brenderup',
  UJG: 'Garia',
  UKR: 'Hero Camper',
  UMT: 'MTDK',
  UN1: 'Ford',
  UU1: 'Dacia',
  UU2: 'Oltcit',
  UU3: 'ARO',
  UU4: 'Roman',
  UU5: 'Rocar',
  UU6: 'Daewoo',
  UU7: 'Euro Bus Diamond',
  UU9: 'Astra Bus',
  UVW: 'UMM',
  UWR: 'Robus',
  UZT: 'UTB',
  U1A: 'Sanos',
  U1V: 'Van Hool',
  U5Y: 'Kia',
  U6A: 'Granus',
  U6Y: 'Kia',
  U6Z: 'Kia',

  // ══════════════════════════════════════
  // === Europe – Austria/France/Spain (V) ===
  // ══════════════════════════════════════
  VAG: 'Puch',
  VAH: 'Hangler',
  VAK: 'Kässbohrer',
  VAN: 'MAN',
  VAV: 'Schwarzmüller',
  VAX: 'Schwingenschlogel',
  VA0: 'ÖAF',
  VA4: 'KSR',
  VBF: 'Fit-Zel',
  VBK: 'KTM',
  VCF: 'Fisker',
  VFA: 'Alpine',
  VFG: 'Caravelair',
  VFK: 'Fruehauf',
  VFN: 'Trailor',
  VF1: 'Renault',
  VF2: 'Renault Trucks',
  VF3: 'Peugeot',
  VF4: 'Talbot',
  VF5: 'Iveco',
  VF6: 'Renault Trucks',
  VF7: 'Citroën',
  VF8: 'Matra',
  VGA: 'Peugeot',
  VGT: 'ASCA',
  VGU: 'Trouillet',
  VGW: 'BSLT',
  VGX: 'Coder',
  VGY: 'Lohr',
  VG5: 'Yamaha',
  VG6: 'Renault Trucks',
  VG7: 'Renault Trucks',
  VG8: 'Renault Trucks',
  VHR: 'Robuste',
  VHX: 'Potain',
  VH1: 'Benalu',
  VH8: 'Microcar',
  VJR: 'Ligier',
  VJY: 'Gruau',
  VJ1: 'Heuliez Bus',
  VJ2: 'Mia Electric',
  VJ4: 'Gruau',
  VKD: 'Cheval Liberté',
  VK1: 'SEG',
  VK2: 'Grandin',
  VK8: 'Venturi',
  VLG: 'Aixam',
  VLU: 'Scania',
  VL4: 'Bluecar',
  VMK: 'Renault',
  VMS: 'Chatenet',
  VMT: 'SECMA',
  VMW: 'Gépébus',
  VM3: 'Lamberet',
  VN1: 'Renault',
  VN4: 'Voxan',
  VNE: 'Iveco Bus',
  VNK: 'Toyota',
  VNV: 'Nissan',
  VRW: 'Goupil',
  VR1: 'DS',
  VR3: 'Peugeot',
  VR7: 'Citroën',
  VPL: 'Nosmoke',
  VP3: 'Magyar',
  VXE: 'Opel',
  VXF: 'Fiat',
  VXK: 'Opel',
  VYC: 'Lancia',
  VYE: 'Jeep',
  VYF: 'Fiat',
  VYJ: 'Ram',
  VYS: 'Renault',
  VZ2: 'Avtomontaža',
  VSA: 'Mercedes-Benz',
  VSC: 'Talbot',
  VSE: 'Suzuki',
  VSF: 'Santana',
  VSK: 'Nissan',
  VSR: 'Leciñena',
  VSS: 'SEAT',
  VSX: 'Opel',
  VSY: 'Renault',
  VS1: 'Pegaso',
  VS5: 'Renault',
  VS6: 'Ford',
  VS7: 'Citroën',
  VS8: 'Peugeot',
  VTD: 'Honda',
  VTH: 'Derbi',
  VTL: 'Yamaha',
  VTM: 'Honda',
  VTP: 'Rieju',
  VTR: 'Gas Gas',
  VTT: 'Suzuki',
  VVC: 'SOR Ibérica',
  VVG: 'Tisvol',
  VV1: 'Lecitrailer',
  VV5: 'Prim-Ball',
  VWA: 'Nissan',
  VWF: 'Guillén',
  VWL: 'Indox',
  VWV: 'Volkswagen',
  VXY: 'Neobus',
  VX1: 'Zastava',
  V1Y: 'Sanos',
  V2X: 'Ikarbus',
  V31: 'TAZ',
  V34: 'Crobus',
  V6A: 'Tiki',
  V6B: 'Brentex',
  V6T: 'Verge',
  V61: 'Respo',

  // ══════════════════════════════════════
  // === Europe – Germany (W) ===
  // ══════════════════════════════════════
  WAC: 'Audi',
  WAF: 'Ackermann',
  WAG: 'Neoplan',
  WAP: 'Alpina',
  WAU: 'Audi',
  WA1: 'Audi',
  WBA: 'BMW',
  WBC: 'Boom Trikes',
  WBJ: 'Bitter',
  WBK: 'Böcker',
  WBL: 'Blumhardt',
  WBS: 'BMW',
  WBU: 'Bürstner',
  WBX: 'BMW',
  WBY: 'BMW',
  WB0: 'Böckmann',
  WB1: 'BMW',
  WB2: 'Blyss',
  WB3: 'BMW',
  WB4: 'BMW',
  WB5: 'BMW',
  WCD: 'Freightliner',
  WCM: 'Wilcox',
  WDA: 'Mercedes-Benz',
  WDB: 'Mercedes-Benz',
  WDC: 'Mercedes-Benz',
  WDD: 'Mercedes-Benz',
  WDF: 'Mercedes-Benz',
  WDP: 'Freightliner',
  WDR: 'Freightliner',
  WDT: 'Dethleffs',
  WDW: 'Dodge',
  WDX: 'Dodge',
  WDY: 'Freightliner',
  WDZ: 'Mercedes-Benz',
  WD0: 'Dodge',
  WD1: 'Freightliner',
  WD2: 'Freightliner',
  WD3: 'Mercedes-Benz',
  WD4: 'Mercedes-Benz',
  WD5: 'Freightliner',
  WD6: 'Freightliner',
  WD7: 'Freightliner',
  WD8: 'Dodge',
  WEB: 'EvoBus',
  WEG: 'Ablinger',
  WEL: 'e.GO',
  WFB: 'Feldbinder',
  WFC: 'Fendt',
  WFD: 'Fliegl',
  WFN: 'Tadano Faun',
  WF0: 'Ford',
  WFO: 'Ford',
  WF1: 'Merkur',
  WGB: 'Göppel Bus',
  WG0: 'Goldhofer',
  WHB: 'Hobby',
  WHD: 'Humbaur',
  WHL: 'Hulco',
  WHW: 'Hako',
  WHY: 'Hymer',
  WH7: 'Hüfferman',
  WJM: 'Iveco',
  WJR: 'Irmscher',
  WKE: 'Krone',
  WKK: 'Setra',
  WKN: 'Knaus',
  WKV: 'Kässbohrer',
  WK0: 'Kögel',
  WLA: 'Langendorf',
  WLF: 'Liebherr',
  WMA: 'MAN',
  WME: 'Smart',
  WMG: 'Demag Cranes',
  WMM: 'Karl Müller',
  WMP: 'M & V',
  WMU: 'Multicar',
  WMW: 'MINI',
  WMX: 'Mercedes-AMG',
  WMZ: 'MINI',
  WNA: 'e.GO',
  WP0: 'Porsche',
  WP1: 'Porsche',
  WPO: 'Porsche',
  WRA: 'Renders',
  WRJ: 'Riese & Müller',
  WSE: 'STEMA',
  WSJ: 'STERK',
  WSK: 'Schmitz Cargobull',
  WSM: 'Schmitz Cargobull',
  WSP: 'Spitzer',
  WSV: 'Aebi Schmidt',
  WS5: 'StreetScooter',
  WS7: 'Sono Motors',
  WTA: 'Tabbert',
  WUA: 'Audi',
  WU1: 'Audi',
  WVG: 'Volkswagen',
  WVM: 'Volkswagen',
  WVP: 'Viseon Bus',
  WVW: 'Volkswagen',
  WV1: 'Volkswagen',
  WV2: 'Volkswagen',
  WV3: 'Volkswagen',
  WV4: 'Volkswagen',
  WV5: 'Volkswagen',
  WWA: 'Wachenhut',
  WWC: 'WM Meyer',
  WZ1: 'Toyota',
  W0D: 'Obermaier',
  W0L: 'Opel',
  W0V: 'Opel',
  W0S: 'Opel',
  W04: 'Buick',
  W06: 'Cadillac',
  W08: 'Saturn',
  W1A: 'Smart',
  W1H: 'Freightliner',
  W1K: 'Mercedes-Benz',
  W1N: 'Mercedes-Benz',
  W1T: 'Mercedes-Benz',
  W1V: 'Mercedes-Benz',
  W1W: 'Mercedes-Benz',
  W1X: 'Mercedes-Benz',
  W1Y: 'Mercedes-Benz',
  W1Z: 'Mercedes-Benz',
  W2W: 'Freightliner',
  W2X: 'Freightliner',
  W2Y: 'Freightliner',
  W2Z: 'Freightliner',

  // ══════════════════════════════════════
  // === Europe – Netherlands (XL) ===
  // ══════════════════════════════════════
  XLA: 'DAF',
  XLB: 'Volvo',
  XLC: 'Ford',
  XLD: 'Pacton',
  XLE: 'Scania',
  XLH: 'Hapert',
  XLJ: 'Anssems',
  XLK: 'Burg',
  XLR: 'DAF',
  XLU: 'Henra',
  XLV: 'DAF',
  XLW: 'Terberg',
  XL3: 'Ebusco',
  XL4: 'Lightyear',
  XMC: 'Mitsubishi',
  XMD: 'Mitsubishi',
  XMG: 'VDL',
  XMR: 'Nooteboom',
  XM4: 'RAVO',
  XNJ: 'Broshuis',
  XNL: 'VDL',
  XNT: 'Pacton',
  XN1: 'Kraker',
  XPN: 'Knapen',
  XPP: 'Atec',
  XRP: 'Proline',
  XRY: 'D-TEC',
  XR7: 'Qarry',

  // ══════════════════════════════════════
  // === Russia/CIS (X) ===
  // ══════════════════════════════════════
  XDN: 'Mercedes-Benz',
  XD2: 'CTTM',
  XEA: 'Avtotor',
  XE2: 'AMKAR',
  XJY: 'Bonum',
  XJ4: 'PKTS',
  XKM: 'Volgabus',
  XP7: 'Tesla',
  XTA: 'Lada',
  XTB: 'Moskvitch',
  XTC: 'KAMAZ',
  XTD: 'LuAZ',
  XTE: 'ZAZ',
  XTF: 'GolAZ',
  XTH: 'GAZ',
  XTJ: 'Lada',
  XTK: 'IzhAvto',
  XTM: 'MAZ',
  XTP: 'Ural',
  XTS: 'ChMZAP',
  XTT: 'UAZ',
  XTU: 'Trolza',
  XTW: 'LAZ',
  XTY: 'LiAZ',
  XTZ: 'ZiL',
  XUF: 'General Motors',
  XUS: 'Nizhegorodets',
  XUU: 'Avtotor',
  XUV: 'Avtotor',
  XUZ: 'InterPipeVAN',
  XU6: 'Avtodom',
  XVG: 'MARZ',
  XVU: 'Start',
  XW7: 'Toyota',
  XW8: 'Volkswagen',
  XWB: 'Daewoo',
  XWE: 'Avtotor',
  XWF: 'Avtotor',
  XX3: 'Ujet',
  XZB: 'SIMAZ',
  XZE: 'Specpricep',
  XZG: 'Great Wall',
  XZP: 'Gut Trailer',
  XZT: 'FoxBus',
  X1D: 'RAF',
  X1E: 'KAvZ',
  X1F: 'NefAZ',
  X1M: 'PAZ',
  X1P: 'Ural',
  X2L: 'Fox Trailer',
  X21: 'Diesel-S',
  X4K: 'Volgabus',
  X4T: 'Sommer',
  X4X: 'Avtotor',
  X5A: 'UralSpetzTrans',
  X6D: 'VIS-AVTO',
  X6S: 'TZA',
  X7L: 'Renault',
  X7M: 'Hyundai',
  X8J: 'Ural',
  X8U: 'Scania',
  X9F: 'Ford',
  X9L: 'GM-AvtoVAZ',
  X9N: 'Samoltor',
  X9P: 'Volvo',
  X9W: 'Brilliance',
  X9X: 'Great Wall',
  X96: 'GAZ',
  X90: 'GRAZ',
  X0T: 'Tonar',

  // ══════════════════════════════════════
  // === Greece (XF/XG) ===
  // ══════════════════════════════════════
  XG3: 'Ecoshift',
  XG4: 'Mpitis',
  XG5: 'Stavropoulos',
  XG6: 'MGK',
  XG8: 'Gorgolis',

  // ══════════════════════════════════════
  // === Europe – Scandinavia/Belgium (Y) ===
  // ══════════════════════════════════════
  YAF: 'Faymonville',
  YAG: 'Syma',
  YAM: 'MAX Trailer',
  YAR: 'Toyota',
  YA2: 'Atlas Copco',
  YA5: 'Renders',
  YBC: 'Toyota',
  YBD: 'Addax',
  YBW: 'Volkswagen',
  YB1: 'Volvo',
  YB2: 'Volvo',
  YB3: 'Volvo',
  YB4: 'LAG',
  YB6: 'Jonckheere',
  YCM: 'Mazda',
  YC1: 'Honda',
  YC3: 'Eduard',
  YD3: 'Chateau',
  YE1: 'Van Hool',
  YE2: 'Van Hool',
  YE6: 'STAS',
  YE7: 'Turbo\'s Hoet',
  YF1: 'Närko',
  YF3: 'NTM',
  YGU: 'JJ-Trailer',
  YH1: 'Solifer',
  YH2: 'BRP',
  YH4: 'Fisker',
  YK1: 'Saab',
  YK2: 'Sisu',
  YK7: 'Sisu',
  YSC: 'Cadillac',
  YSM: 'Polestar',
  YSP: 'Volta Trucks',
  YSR: 'Polestar',
  YS2: 'Scania',
  YS3: 'Saab',
  YS4: 'Scania',
  YS5: 'OmniNova',
  YS7: 'Solifer',
  YTN: 'NEVS',
  YT7: 'Kabe',
  YU1: 'Brenderup',
  YU7: 'Husaberg',
  YVV: 'WiMa',
  YV1: 'Volvo',
  YV2: 'Volvo',
  YV3: 'Volvo',
  YV4: 'Volvo',
  YV5: 'Volvo',
  YYB: 'Tysse',
  YYC: 'Think',
  Y3D: 'MTM',
  Y3F: 'Neman',
  Y3J: 'Belkommunmash',
  Y3K: 'Neman Bus',
  Y3M: 'MAZ',
  Y3W: 'VFV',
  Y4F: 'Ford',
  Y4K: 'Geely',
  Y6B: 'Iveco',
  Y6D: 'ZAZ',
  Y6E: 'LAZ',
  Y6J: 'Bogdan',
  Y6L: 'Bogdan',
  Y6U: 'Škoda',
  Y6W: 'PGFM',
  Y6Y: 'LEV',
  Y7A: 'KrAZ',
  Y7B: 'Bogdan',
  Y7C: 'Great Wall',
  Y7D: 'GAZ',
  Y7F: 'BAZ',
  Y7S: 'Korida-Tech',
  Y7W: 'Geely',
  Y7X: 'Ruta',
  Y8A: 'LAZ',
  Y8H: 'UNV Leader',
  Y8S: 'Ximmash',
  Y8X: 'GAZ',
  Y9A: 'PAVAM',
  Y9H: 'LAZ',
  Y9M: 'AMS',
  Y9T: 'Dnipro',
  Y9W: 'Pragmatec',
  Y9Z: 'Lada',

  // ══════════════════════════════════════
  // === Europe – Italy (Z) ===
  // ══════════════════════════════════════
  ZAA: 'Alfa Romeo',
  ZAC: 'Jeep',
  ZAH: 'Rolfo',
  ZAJ: 'Trigano',
  ZAM: 'Maserati',
  ZAP: 'Piaggio',
  ZAR: 'Alfa Romeo',
  ZAS: 'Alfa Romeo',
  ZAX: 'Zorzi',
  ZA4: 'Omar',
  ZA0: 'Acerbi',
  ZBA: 'Piacenza',
  ZBB: 'Bertone',
  ZBD: 'InBus',
  ZBN: 'Benelli',
  ZBW: 'Rayton-Fissore',
  ZB3: 'Cardi',
  ZCB: 'Bartoletti',
  ZCF: 'Iveco',
  ZCG: 'MV Agusta',
  ZCM: 'Menarinibus',
  ZCN: 'Astra',
  ZCV: 'Vibreti',
  ZCZ: 'BredaBus',
  ZC1: 'AnsaldoBreda',
  ZC2: 'Chrysler',
  ZD4: 'Aprilia',
  ZDC: 'Honda',
  ZDF: 'Ferrari',
  ZDJ: 'ACM Biagini',
  ZDM: 'Ducati',
  ZDT: 'De Tomaso',
  ZDY: 'Cacciamali',
  ZD0: 'Yamaha',
  ZD3: 'Beta Motor',
  ZD5: 'Casalini',
  ZEB: 'Ellebi',
  ZEH: 'Trigano',
  ZES: 'Bimota',
  ZEX: 'TM Racing',
  ZE5: 'Carmosino',
  ZFA: 'Fiat',
  ZFB: 'Fiat',
  ZFC: 'Fiat',
  ZFE: 'KL Motorcycle',
  ZFF: 'Ferrari',
  ZFJ: 'Pezzaioli',
  ZFM: 'Fantic Motor',
  ZFR: 'Pininfarina',
  ZF4: 'Qvale',
  ZGA: 'Iveco Bus',
  ZGP: 'Merker',
  ZGU: 'Moto Guzzi',
  ZG2: 'FAAM',
  ZHU: 'Husqvarna',
  ZHW: 'Lamborghini',
  ZHZ: 'Menci',
  ZH5: 'FB Mondial',
  ZJM: 'Malaguti',
  ZJN: 'Innocenti',
  ZJT: 'Italjet',
  ZKC: 'Ducati Energia',
  ZKH: 'Husqvarna',
  ZLA: 'Lancia',
  ZLF: 'Tazzari',
  ZLM: 'Moto Morini',
  ZLV: 'Laverda',
  ZMA: 'Maserati',
  ZN6: 'Maserati',
  ZNN: 'Energica',
  ZN0: 'SWM',
  ZN3: 'Iveco',
  ZPB: 'Lamborghini',
  ZPY: 'DR Automobiles',
  ZP6: 'XEV',
  ZP8: 'Regis Motors',
  ZRG: 'Tazzari',
  ZR1: 'Microlino',
  ZSG: 'Ferrari',
  ZX1: 'TAM',
  ZY1: 'Adria',
  ZZ1: 'Tomos',

  // === Russia via Z ===
  Z6F: 'Ford',
  Z7C: 'Luidor',
  Z7N: 'KAvZ',
  Z7T: 'RoAZ',
  Z7X: 'Isuzu',
  Z76: 'SEMAZ',
  Z8M: 'Marussia',
  Z8N: 'Nissan',
  Z8T: 'PCMA',
  Z8Y: 'Nasteviya',
  Z9B: 'KuzbassAvto',
  Z9M: 'Mercedes-Benz',
  Z9N: 'Iveco',
  Z94: 'Hyundai',
  Z07: 'Volgabus',

  // ══════════════════════════════════════
  // === North America – US (1) ===
  // ══════════════════════════════════════
  '1AC': 'AMC',
  '1AF': 'American LaFrance',
  '1AJ': 'Ajax',
  '1AM': 'AMC',
  '1BA': 'Blue Bird',
  '1BB': 'Blue Bird',
  '1BD': 'Blue Bird',
  '1BL': 'Balko',
  '1BN': 'Beall',
  '1B3': 'Dodge',
  '1B4': 'Dodge',
  '1B6': 'Dodge',
  '1B7': 'Dodge',
  '1CM': 'Checker',
  '1CU': 'Cushman',
  '1CY': 'Crane Carrier',
  '1C3': 'Chrysler',
  '1C4': 'Chrysler',
  '1C6': 'Ram',
  '1C8': 'Chrysler',
  '1D3': 'Dodge',
  '1D4': 'Dodge',
  '1D7': 'Dodge',
  '1D8': 'Dodge',
  '1DW': 'Stoughton',
  '1EU': 'Eagle Coach',
  '1FA': 'Ford',
  '1FB': 'Ford',
  '1FC': 'Ford',
  '1FD': 'Ford',
  '1FM': 'Ford',
  '1FT': 'Ford',
  '1FU': 'Freightliner',
  '1FV': 'Freightliner',
  '1F1': 'Ford',
  '1F6': 'Ford',
  '1G0': 'Opel',
  '1G1': 'Chevrolet',
  '1G2': 'Pontiac',
  '1G3': 'Oldsmobile',
  '1G4': 'Buick',
  '1G5': 'GMC',
  '1G6': 'Cadillac',
  '1G7': 'Pontiac',
  '1G8': 'Saturn',
  '1GA': 'Chevrolet',
  '1GB': 'Chevrolet',
  '1GC': 'Chevrolet',
  '1GD': 'GMC',
  '1GE': 'Cadillac',
  '1GF': 'Flxible',
  '1GG': 'Isuzu',
  '1GH': 'Oldsmobile',
  '1GJ': 'GMC',
  '1GK': 'GMC',
  '1GM': 'Pontiac',
  '1GN': 'Chevrolet',
  '1GR': 'Great Dane',
  '1GT': 'GMC',
  '1GY': 'Cadillac',
  '1HA': 'Chevrolet',
  '1HD': 'Harley-Davidson',
  '1HF': 'Honda',
  '1HG': 'Honda',
  '1HS': 'International',
  '1HT': 'International',
  '1HV': 'IC Bus',
  '1JC': 'Jeep',
  '1JJ': 'Wabash',
  '1JT': 'Jeep',
  '1JU': 'Marmon',
  '1J4': 'Jeep',
  '1J7': 'Jeep',
  '1J8': 'Jeep',
  '1LH': 'Landoll',
  '1LJ': 'Lincoln',
  '1LN': 'Lincoln',
  '1LV': 'Lectra',
  '1L0': 'Lufkin',
  '1L1': 'Lincoln',
  '1MB': 'Mercedes-Benz',
  '1ME': 'Mercury',
  '1MR': 'Lincoln',
  '1M0': 'John Deere',
  '1M1': 'Mack',
  '1M2': 'Mack',
  '1M3': 'Mack',
  '1M4': 'Mack',
  '1M8': 'Motor Coach Industries',
  '1NK': 'Kenworth',
  '1NL': 'Gulf Stream',
  '1NN': 'Monon',
  '1NP': 'Peterbilt',
  '1NX': 'Toyota',
  '1N4': 'Nissan',
  '1N6': 'Nissan',
  '1P3': 'Plymouth',
  '1P4': 'Plymouth',
  '1P7': 'Plymouth',
  '1PM': 'Polar Tank',
  '1PT': 'Trailmobile',
  '1PY': 'John Deere',
  '1RF': 'Roadmaster',
  '1RN': 'Reitnouer',
  '1ST': 'Airstream',
  '1S1': 'Strick',
  '1TD': 'Timpte',
  '1TK': 'Trail King',
  '1T7': 'Thomas Built',
  '1T8': 'Thomas Built',
  '1TC': 'Coachmen',
  '1TU': 'TMC',
  '1UJ': 'Jayco',
  '1UT': 'AM General',
  '1UY': 'Utility Trailer',
  '1VH': 'Orion',
  '1VW': 'Volkswagen',
  '1V1': 'Volkswagen',
  '1V2': 'Volkswagen',
  '1WT': 'Winnebago',
  '1WU': 'White',
  '1WV': 'Winnebago',
  '1WW': 'Winnebago',
  '1WX': 'White',
  '1WY': 'White',
  '1W8': 'Witzco',
  '1XA': 'Excalibur',
  '1XK': 'Kenworth',
  '1XM': 'Renault',
  '1XP': 'Peterbilt',
  '1YJ': 'Rokon',
  '1YV': 'Mazda',
  '1ZV': 'Ford',
  '1ZW': 'Mercury',
  '1Z3': 'Mitsubishi',
  '1Z7': 'Mitsubishi',
  '10B': 'Brenner',
  '10R': 'E-Z-GO',
  '10T': 'Oshkosh',
  '11H': 'Hendrickson',
  '12A': 'Avanti',
  '137': 'AM General',
  '13N': 'Fontaine',
  '15G': 'Gillig',
  '16C': 'Clenet',
  '16X': 'Vixen',
  '17N': 'John Deere',
  '19U': 'Acura',
  '19V': 'Acura',
  '19X': 'Honda',

  // === North America – Canada (2) ===
  '2A3': 'Imperial',
  '2A4': 'Chrysler',
  '2A8': 'Chrysler',
  '2AY': 'Hino',
  '2AZ': 'Hino',
  '2BC': 'Jeep',
  '2BP': 'Ski-Doo',
  '2BV': 'Can-Am',
  '2BW': 'Can-Am',
  '2BX': 'Can-Am',
  '2BZ': 'Can-Am',
  '2B1': 'Orion',
  '2B3': 'Dodge',
  '2B4': 'Dodge',
  '2B5': 'Dodge',
  '2B6': 'Dodge',
  '2B7': 'Dodge',
  '2C1': 'Chevrolet',
  '2C3': 'Chrysler',
  '2C4': 'Chrysler',
  '2C7': 'Pontiac',
  '2C8': 'Chrysler',
  '2CC': 'AMC',
  '2CG': 'Pontiac',
  '2CK': 'GMC',
  '2CM': 'AMC',
  '2CN': 'Chevrolet',
  '2CT': 'GMC',
  '2D4': 'Dodge',
  '2D6': 'Dodge',
  '2D7': 'Dodge',
  '2D8': 'Dodge',
  '2DG': 'Ontario Drive',
  '2DM': 'Di-Mond',
  '2DN': 'Dynasty',
  '2EZ': 'Electra Meccanica',
  '2E3': 'Eagle',
  '2E4': 'Lancia',
  '2FA': 'Ford',
  '2FH': 'Zenn',
  '2FM': 'Ford',
  '2FT': 'Ford',
  '2FU': 'Freightliner',
  '2FV': 'Freightliner',
  '2FW': 'Sterling',
  '2FY': 'New Flyer',
  '2FZ': 'Sterling',
  '2G0': 'GMC',
  '2G1': 'Chevrolet',
  '2G2': 'Pontiac',
  '2G3': 'Oldsmobile',
  '2G4': 'Buick',
  '2G5': 'Chevrolet',
  '2G6': 'Cadillac',
  '2G7': 'Pontiac',
  '2G8': 'Chevrolet',
  '2GA': 'Chevrolet',
  '2GB': 'Chevrolet',
  '2GC': 'Chevrolet',
  '2GD': 'GMC',
  '2GE': 'Cadillac',
  '2GH': 'GMC',
  '2GJ': 'GMC',
  '2GK': 'GMC',
  '2GN': 'Chevrolet',
  '2GT': 'GMC',
  '2HG': 'Honda',
  '2HH': 'Acura',
  '2HJ': 'Honda',
  '2HK': 'Honda',
  '2HM': 'Hyundai',
  '2HN': 'Acura',
  '2HS': 'International',
  '2HT': 'International',
  '2J4': 'Jeep',
  '2L1': 'Lincoln',
  '2LD': 'Triple E',
  '2LJ': 'Lincoln',
  '2LM': 'Lincoln',
  '2LN': 'Lincoln',
  '2M1': 'Mack',
  '2M2': 'Mack',
  '2ME': 'Mercury',
  '2MG': 'Motor Coach Industries',
  '2MH': 'Mercury',
  '2MR': 'Mercury',
  '2NK': 'Kenworth',
  '2NP': 'Peterbilt',
  '2NV': 'Nova Bus',
  '2P3': 'Plymouth',
  '2P4': 'Plymouth',
  '2P5': 'Plymouth',
  '2PC': 'Prevost',
  '2S2': 'Suzuki',
  '2S3': 'Suzuki',
  '2TU': 'Tri-Star',
  '2T1': 'Toyota',
  '2T2': 'Lexus',
  '2T3': 'Toyota',
  '2V4': 'Volkswagen',
  '2V8': 'Volkswagen',
  '2WK': 'Western Star',
  '2WL': 'Western Star',
  '2WM': 'Western Star',
  '2XK': 'Kenworth',
  '2XM': 'Eagle',
  '2XP': 'Peterbilt',

  // === North America – Mexico (3) ===
  '3AK': 'Freightliner',
  '3AL': 'Freightliner',
  '3AW': 'Fruehauf',
  '3AX': 'Scania',
  '3BE': 'Scania',
  '3BJ': 'Western Star',
  '3BK': 'Kenworth',
  '3BM': 'Motor Coach Industries',
  '3BP': 'Peterbilt',
  '3B3': 'Dodge',
  '3B4': 'Dodge',
  '3B6': 'Dodge',
  '3B7': 'Dodge',
  '3C3': 'Chrysler',
  '3C4': 'Chrysler',
  '3C6': 'Chrysler',
  '3C7': 'Chrysler',
  '3C8': 'Chrysler',
  '3CA': 'Chrysler',
  '3CE': 'Volvo',
  '3CG': 'KTMMEX',
  '3CZ': 'Honda',
  '3D2': 'Dodge',
  '3D3': 'Dodge',
  '3D4': 'Dodge',
  '3D6': 'Dodge',
  '3D7': 'Dodge',
  '3E4': 'Fiat',
  '3FA': 'Ford',
  '3FC': 'Ford',
  '3FE': 'Ford',
  '3FM': 'Ford',
  '3FN': 'Ford',
  '3FR': 'Ford',
  '3FT': 'Ford',
  '3F6': 'Sterling',
  '3G0': 'Holden',
  '3G1': 'Chevrolet',
  '3G2': 'Pontiac',
  '3G4': 'Buick',
  '3G5': 'Buick',
  '3G7': 'Pontiac',
  '3GC': 'Chevrolet',
  '3GK': 'GMC',
  '3GM': 'Holden',
  '3GN': 'Chevrolet',
  '3GP': 'Honda',
  '3GS': 'Saturn',
  '3GT': 'GMC',
  '3GY': 'Cadillac',
  '3H1': 'Honda',
  '3H3': 'Hyundai',
  '3HA': 'International',
  '3HC': 'International',
  '3HD': 'Acura',
  '3HG': 'Honda',
  '3HS': 'International',
  '3HT': 'International',
  '3HV': 'International',
  '3JB': 'Can-Am',
  '3KM': 'Kia',
  '3KP': 'Kia',
  '3LN': 'Lincoln',
  '3MA': 'Mercury',
  '3MD': 'Mazda',
  '3ME': 'Mercury',
  '3MF': 'BMW',
  '3MJ': 'Mazda',
  '3MV': 'Mazda',
  '3MW': 'BMW',
  '3MY': 'Toyota',
  '3MZ': 'Mazda',
  '3N1': 'Nissan',
  '3N6': 'Nissan',
  '3N8': 'Nissan',
  '3NE': 'Polaris',
  '3NS': 'Polaris',
  '3P3': 'Plymouth',
  '3PC': 'Infiniti',
  '3TM': 'Toyota',
  '3TY': 'Toyota',
  '3VV': 'Volkswagen',
  '3VW': 'Volkswagen',
  '3WK': 'Kenworth',
  '3WP': 'Peterbilt',

  // === US (4) ===
  '4A3': 'Mitsubishi',
  '4A4': 'Mitsubishi',
  '4B3': 'Dodge',
  '4C3': 'Chrysler',
  '4C6': 'Reinke',
  '4CD': 'Oshkosh',
  '4DR': 'IC Bus',
  '4E3': 'Eagle',
  '4EN': 'E-ONE',
  '4F2': 'Mazda',
  '4F4': 'Mazda',
  '4G1': 'Chevrolet',
  '4G2': 'Pontiac',
  '4G3': 'Toyota',
  '4G5': 'General Motors',
  '4GD': 'Opel',
  '4GL': 'Buick',
  '4GT': 'Isuzu',
  '4J8': 'LBT',
  '4JG': 'Mercedes-Benz',
  '4KB': 'Chevrolet',
  '4KD': 'GMC',
  '4KE': 'US Electricar',
  '4KL': 'Isuzu',
  '4LM': 'Capacity',
  '4M2': 'Mercury',
  '4MB': 'Mitsubishi',
  '4ML': 'Oshkosh',
  '4MZ': 'Buell',
  '4N2': 'Nissan',
  '4NU': 'Isuzu',
  '4P1': 'Pierce',
  '4P3': 'Mitsubishi',
  '4RK': 'Nova Bus',
  '4S1': 'Isuzu',
  '4S2': 'Isuzu',
  '4S3': 'Subaru',
  '4S4': 'Subaru',
  '4S6': 'Honda',
  '4S7': 'Spartan',
  '4T1': 'Toyota',
  '4T3': 'Toyota',
  '4T4': 'Toyota',
  '4TA': 'Toyota',
  '4UF': 'Arctic Cat',
  '4US': 'BMW',
  '4UZ': 'Freightliner',
  '4V0': 'Crossroads',
  '4V1': 'White',
  '4V2': 'White',
  '4V3': 'Volvo',
  '4V4': 'Volvo',
  '4V5': 'Volvo',
  '4V6': 'Volvo',
  '4VA': 'Volvo',
  '4VE': 'Volvo',
  '4VG': 'Volvo',
  '4VH': 'Volvo',
  '4VM': 'Volvo',
  '4VZ': 'Spartan',
  '4WW': 'Wilson',
  '4W1': 'Chevrolet',
  '4W5': 'Acura',
  '4XA': 'Polaris',
  '4X4': 'Forest River',
  '4YD': 'KeyStone',
  '4YM': 'Carry-On',
  '43C': 'Consulier',
  '44K': 'HME',
  '46G': 'Gillig',
  '46J': 'Federal Motors',
  '478': 'Honda',
  '480': 'Sterling',
  '49H': 'Sterling',

  // === US (5) ===
  '5AS': 'GEM',
  '5AX': 'Armor Chassis',
  '5A4': 'Load Rite',
  '5BP': 'Solectria',
  '5BZ': 'Nissan',
  '5B4': 'Workhorse',
  '5CD': 'Indian',
  '5CX': 'Shelby',
  '5DF': 'Thomas Dennis',
  '5DG': 'Terex',
  '5EH': 'Excelsior-Henderson',
  '5EO': 'Cottrell',
  '5FC': 'Columbia',
  '5FN': 'Honda',
  '5FP': 'Honda',
  '5FR': 'Acura',
  '5FT': 'Feeling',
  '5FY': 'New Flyer',
  '5GA': 'Buick',
  '5GD': 'Daewoo',
  '5GN': 'Hummer',
  '5GR': 'Hummer',
  '5GT': 'Hummer',
  '5GZ': 'Saturn',
  '5G8': 'Holden',
  '5HD': 'Harley-Davidson',
  '5HT': 'Heil',
  '5J5': 'Club Car',
  '5J6': 'Honda',
  '5J8': 'Acura',
  '5KB': 'Honda',
  '5KJ': 'Western Star',
  '5KK': 'Western Star',
  '5KM': 'Vento',
  '5KT': 'Karavan',
  '5L1': 'Lincoln',
  '5L5': 'American IronHorse',
  '5LD': 'Lincoln',
  '5LM': 'Lincoln',
  '5LT': 'Lincoln',
  '5MZ': 'Buell',
  '5N1': 'Nissan',
  '5N3': 'Infiniti',
  '5NH': 'Forest River',
  '5NM': 'Hyundai',
  '5NP': 'Hyundai',
  '5NT': 'Hyundai',
  '5PV': 'Hino',
  '5RJ': 'Android Industries',
  '5RX': 'Heartland',
  '5SA': 'Suzuki',
  '5SX': 'American LaFrance',
  '5S3': 'Saab',
  '5TB': 'Toyota',
  '5TD': 'Toyota',
  '5TE': 'Toyota',
  '5TF': 'Toyota',
  '5TU': 'CTS',
  '5UM': 'BMW',
  '5UX': 'BMW',
  '5VC': 'Autocar',
  '5VF': 'American Electric',
  '5VP': 'Victory',
  '5V8': 'Vanguard',
  '5WE': 'IC Bus',
  '5XX': 'Kia',
  '5XY': 'Kia',
  '5YA': 'Indian',
  '5YF': 'Toyota',
  '5YJ': 'Tesla',
  '5YM': 'BMW',
  '5YN': 'Cruise Car',
  '5Y2': 'Pontiac',
  '5Y4': 'Yamaha',
  '5ZT': 'Forest River',
  '5ZU': 'Greenkraft',
  '5Z6': 'Suzuki',
  '50E': 'Lucid',
  '50G': 'Karma',
  '516': 'Autocar',
  '51R': 'Brammo',
  '522': 'GreenGo',
  '523': 'VPG',
  '52C': 'GEM',
  '537': 'Azure Dynamics',
  '538': 'Zero Motorcycles',
  '53G': 'Coda',
  '53T': 'Think',
  '546': 'EBR',
  '54C': 'Winnebago',
  '54D': 'Isuzu',
  '54F': 'Rosenbauer',
  '55S': 'Mercedes-Benz',
  '56K': 'Indian',
  '573': 'Grand Design',
  '57C': 'Maurer',
  '57R': 'Oreion',
  '57S': 'Lightning Motors',
  '57W': 'Mobility Ventures',
  '57X': 'Polaris',
  '58A': 'Lexus',

  // === Oceania (6) ===
  '6AB': 'MAN',
  '6AM': 'Jayco',
  '6F1': 'Ford',
  '6F2': 'Iveco',
  '6F4': 'Nissan',
  '6F5': 'Kenworth',
  '6FM': 'Mack',
  '6FP': 'Ford',
  '6G1': 'Holden',
  '6G2': 'Pontiac',
  '6G3': 'Chevrolet',
  '6H8': 'Holden',
  '6KT': 'BCI Bus',
  '6MM': 'Mitsubishi',
  '6MP': 'Mercury',
  '6T1': 'Toyota',
  '6T9': 'Trailer',
  '6U9': 'Private Import',
  '6ZZ': 'Private Import',

  // === New Zealand (7A) ===
  '7AB': 'MAN',
  '7AT': 'New Zealand',
  '7A1': 'Mitsubishi',
  '7A3': 'Honda',
  '7A4': 'Toyota',
  '7A5': 'Ford',
  '7A7': 'Nissan',
  '7A8': 'New Zealand',

  // === US (7) ===
  '7FA': 'Honda',
  '7FC': 'Rivian',
  '7F7': 'Arcimoto',
  '7GZ': 'GMC',
  '7G0': 'Faraday Future',
  '7G2': 'Tesla',
  '7H4': 'Hino',
  '7H8': 'Cenntro',
  '7JD': 'Volvo',
  '7JR': 'Volvo',
  '7JZ': 'Proterra',
  '7KG': 'Vanderhall',
  '7KY': 'Dorsey',
  '7MM': 'Mazda',
  '7MU': 'Toyota',
  '7MW': 'Cenntro',
  '7MZ': 'HDK',
  '7NA': 'Navistar',
  '7NY': 'Lordstown',
  '7PD': 'Rivian',
  '7RZ': 'Electric Last Mile',
  '7SA': 'Tesla',
  '7SU': 'Blue Arc',
  '7SV': 'Toyota',
  '7SX': 'GEM',
  '7SY': 'Polestar',
  '7TN': 'Canoo',
  '7UU': 'Lucid',
  '7UZ': 'Kaufman',
  '7VV': 'Ree Automotive',
  '7WE': 'Bollinger',
  '7YA': 'Hyundai',
  '7Z0': 'Zoox',
  '722': 'Isuzu',

  // === South America (8) ===
  '8AB': 'Mercedes-Benz',
  '8AC': 'Mercedes-Benz',
  '8AD': 'Peugeot',
  '8AE': 'Peugeot',
  '8AF': 'Ford',
  '8AG': 'Chevrolet',
  '8AJ': 'Toyota',
  '8AK': 'Suzuki',
  '8AN': 'Nissan',
  '8AP': 'Fiat',
  '8AT': 'Iveco',
  '8AW': 'Volkswagen',
  '8A1': 'Renault',
  '8A3': 'Scania',
  '8BB': 'Agrale',
  '8BC': 'Citroën',
  '8BN': 'Mercedes-Benz',
  '8BR': 'Mercedes-Benz',
  '8BT': 'Mercedes-Benz',
  '8BU': 'Mercedes-Benz',
  '8CH': 'Honda',
  '8C3': 'Honda',
  '8G1': 'Renault',
  '8GD': 'Peugeot',
  '8GG': 'Chevrolet',
  '8LD': 'Chevrolet',
  '8LF': 'Mazda',
  '8LG': 'Hyundai',
  '8L4': 'Great Wall',
  '8XD': 'Ford',
  '8XJ': 'Mack',
  '8XV': 'Iveco',
  '8Z1': 'Chevrolet',
  '829': 'Quantum',

  // === South America (9) ===
  '9BD': 'Fiat',
  '9BF': 'Ford',
  '9BG': 'Chevrolet',
  '9BH': 'Hyundai',
  '9BM': 'Mercedes-Benz',
  '9BN': 'Mafersa',
  '9BR': 'Toyota',
  '9BS': 'Scania',
  '9BV': 'Volvo',
  '9BW': 'Volkswagen',
  '9BY': 'Agrale',
  '9C2': 'Honda',
  '9C6': 'Yamaha',
  '9CD': 'Suzuki',
  '9DW': 'Kenworth',
  '92H': 'Origem',
  '932': 'Harley-Davidson',
  '935': 'Citroën',
  '936': 'Peugeot',
  '937': 'Dodge',
  '93C': 'Chevrolet',
  '93H': 'Honda',
  '93K': 'Volvo',
  '93P': 'Volare',
  '93R': 'Toyota',
  '93S': 'Navistar',
  '93U': 'Audi',
  '93V': 'Navistar',
  '93W': 'Fiat',
  '93X': 'Mitsubishi',
  '93Y': 'Renault',
  '93Z': 'Iveco',
  '94D': 'Nissan',
  '94N': 'RWM',
  '94T': 'Troller',
  '95P': 'CAOA',
  '95V': 'Dafra',
  '95Z': 'Buell',
  '953': 'MAN',
  '96P': 'Kawasaki',
  '97N': 'Triumph',
  '988': 'Jeep',
  '98M': 'BMW',
  '98P': 'DAF',
  '98R': 'Chery',
  '99A': 'Audi',
  '99H': 'Shineray',
  '99J': 'Jaguar',
  '99K': 'Haojue',
  '99L': 'BYD',
  '99Z': 'BMW',
  '9FB': 'Renault',
  '9FC': 'Mazda',
  '9GA': 'Chevrolet',
  '9UJ': 'Chery',
  '9UK': 'Lifan',
  '9UT': 'Dongfeng',
  '9UW': 'Kia',
  '9VC': 'Fiat',
  '9V7': 'Citroën',
  '9V8': 'Peugeot',

  // === Other ===
  B7J: 'Chrysler',
  CL9: 'Wallyscar',
  S2D: 'Chrysler',
};
